In [1]:
!pip install -q transformers sentencepiece x-transformers optuna scikit-learn
!apt-get -qq update
!apt-get -qq install -y unrar

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 107.3/107.3 kB 3.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.1/143.1 kB 7.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 163.8/163.8 kB 8.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.6/61.6 kB 3.0 MB/s eta 0:00:00
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)

# mBERT + x-transformers — Original SIED-Thai — Strong Optimized

เวอร์ชันนี้เปลี่ยนเฉพาะ encoder เป็น `bert-base-multilingual-cased` และใช้ **SIED-Thai ตัวต้นฉบับที่ยังไม่ balance**

- ใช้ `SIED-Thai.csv` จาก archive ที่ผู้ใช้อัปโหลด
- 2,400 แถว
- Labels: Happiness, Sadness, Anger, Disgust, Surprise, Fear
- split 70/15/15 ด้วย `SEED=42` และ stratify ตาม label combination
- คง `MAX_LEN=128`, `EPOCHS=100`, `BATCH_SIZE=64`
- คง Optuna Strong Optimized framework เดิม: `N_TRIALS=25`, `OPTUNA_EPOCHS=35`
- encoder frozen
- decoder, pooling, classifier, loss search, threshold tuning และ objective คงเดิม

In [2]:
import os
import json
import random
import warnings
import subprocess
import shutil
from pathlib import Path
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd

from tqdm import tqdm

import torch
import torch.nn as nn

from torch.utils.data import Dataset, DataLoader

from transformers import (
    AutoTokenizer,
    AutoModel,
    get_linear_schedule_with_warmup
)

from x_transformers import Decoder

from sklearn.model_selection import train_test_split

from sklearn.metrics import (
    f1_score,
    accuracy_score,
    precision_score,
    recall_score,
    classification_report,
    hamming_loss,
    multilabel_confusion_matrix
)

import optuna

In [3]:
SEED = 42

random.seed(SEED)
np.random.seed(SEED)

torch.manual_seed(SEED)
torch.cuda.manual_seed_all(SEED)

In [4]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print("DEVICE:", device)

DEVICE: cuda

In [5]:
MODEL_NAME = "bert-base-multilingual-cased"

MAX_LEN = 128
EPOCHS = 100
BATCH_SIZE = 64
NUM_LABELS = 6

N_TRIALS = 25
OPTUNA_EPOCHS = 35

LABEL_COLUMNS = [
    "Happiness",
    "Sadness",
    "Anger",
    "Disgust",
    "Surprise",
    "Fear"
]

TEXT_COLUMN = "Tweets"

In [6]:
# ถ้าใช้ไฟล์ .rar ที่อัปโหลดมาโดยตรงใน Google Colab
RAR_PATH = "/content/SIED-Thai.rar"
CSV_PATH = "/kaggle/input/datasets/kmkimmy/sied-thai/SIED-Thai.csv"
EXTRACT_ROOT = "/content/sied_thai_extracted"

if not os.path.exists(CSV_PATH) and os.path.exists(RAR_PATH):
    os.makedirs(EXTRACT_ROOT, exist_ok=True)

    if shutil.which("unrar") is None:
        raise RuntimeError(
            "ไม่พบคำสั่ง unrar กรุณารัน cell ติดตั้งด้านบนก่อน "
            "หรือ extract SIED-Thai.rar แล้วอัปโหลด SIED-Thai.csv"
        )

    subprocess.run(
        ["unrar", "x", "-o+", RAR_PATH, EXTRACT_ROOT + "/"],
        check=True
    )

    CSV_PATH = os.path.join(EXTRACT_ROOT, "SIED-Thai.csv")

# fallback สำหรับ local/sandbox
if not os.path.exists(CSV_PATH):
    CSV_PATH = "/kaggle/input/datasets/kmkimmy/sied-thai/SIED-Thai.csv"

print("SIED CSV:", CSV_PATH)


df = pd.read_csv(CSV_PATH)

required_columns = [TEXT_COLUMN] + LABEL_COLUMNS

for col in required_columns:
    if col not in df.columns:
        raise ValueError(f"dataset ไม่มี column: {col}")

df = df[required_columns].copy()
df[TEXT_COLUMN] = df[TEXT_COLUMN].astype(str).str.strip()

for col in LABEL_COLUMNS:
    df[col] = pd.to_numeric(
        df[col],
        errors="coerce"
    ).fillna(0).astype(int)

print("TOTAL ROWS:", len(df))
print("\nORIGINAL LABEL DISTRIBUTION")
print(df[LABEL_COLUMNS].sum())

print("\nORIGINAL LABEL CARDINALITY")
print(df[LABEL_COLUMNS].sum(axis=1).value_counts().sort_index())

SIED CSV: /kaggle/input/datasets/kmkimmy/sied-thai/SIED-Thai.csv
TOTAL ROWS: 2400

ORIGINAL LABEL DISTRIBUTION
Happiness     170
Sadness      1886
Anger         312
Disgust       467
Surprise      162
Fear          304
dtype: int64

ORIGINAL LABEL CARDINALITY
0     112
1    1460
2     659
3     153
4      16
Name: count, dtype: int64

In [7]:
# Original SIED-Thai ไม่มี train/validation/test แยกมาให้
# ใช้ split 70/15/15 เหมือน Strong Optimized framework
# และใช้ stratify ตาม label combination เพื่อลดความคลาดเคลื่อนของ class distribution

def make_stratify_key(frame):
    label_part = frame[LABEL_COLUMNS].astype(str).agg("".join, axis=1)
    card_part = frame[LABEL_COLUMNS].sum(axis=1).astype(str)
    key = card_part + "_" + label_part

    counts = key.value_counts()
    key = key.where(key.map(counts) >= 2, "rare")

    return key


stratify_key = make_stratify_key(df)

train_df, temp_df = train_test_split(
    df,
    test_size=0.30,
    random_state=SEED,
    shuffle=True,
    stratify=stratify_key
)

temp_stratify_key = make_stratify_key(temp_df)

val_df, test_df = train_test_split(
    temp_df,
    test_size=0.50,
    random_state=SEED,
    shuffle=True,
    stratify=temp_stratify_key
)

train_df = train_df.reset_index(drop=True)
val_df = val_df.reset_index(drop=True)
test_df = test_df.reset_index(drop=True)

print("TRAIN:", len(train_df))
print("VALIDATION:", len(val_df))
print("TEST:", len(test_df))

print("\nTRAIN LABEL DISTRIBUTION")
print(train_df[LABEL_COLUMNS].sum())

print("\nVAL LABEL DISTRIBUTION")
print(val_df[LABEL_COLUMNS].sum())

print("\nTEST LABEL DISTRIBUTION")
print(test_df[LABEL_COLUMNS].sum())

print("\nTRAIN LABEL CARDINALITY")
print(train_df[LABEL_COLUMNS].sum(axis=1).value_counts().sort_index())

print("\nVAL LABEL CARDINALITY")
print(val_df[LABEL_COLUMNS].sum(axis=1).value_counts().sort_index())

print("\nTEST LABEL CARDINALITY")
print(test_df[LABEL_COLUMNS].sum(axis=1).value_counts().sort_index())

TRAIN: 1680
VALIDATION: 360
TEST: 360

TRAIN LABEL DISTRIBUTION
Happiness     119
Sadness      1320
Anger         218
Disgust       328
Surprise      112
Fear          212
dtype: int64

VAL LABEL DISTRIBUTION
Happiness     25
Sadness      282
Anger         48
Disgust       67
Surprise      24
Fear          48
dtype: int64

TEST LABEL DISTRIBUTION
Happiness     26
Sadness      284
Anger         46
Disgust       72
Surprise      26
Fear          44
dtype: int64

TRAIN LABEL CARDINALITY
0      78
1    1023
2     461
3     108
4      10
Name: count, dtype: int64

VAL LABEL CARDINALITY
0     17
1    220
2     98
3     22
4      3
Name: count, dtype: int64

TEST LABEL CARDINALITY
0     17
1    217
2    100
3     23
4      3
Name: count, dtype: int64

In [8]:
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/625 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

In [9]:
class EmotionDataset(Dataset):

    def __init__(self, df):

        self.texts = df[TEXT_COLUMN].tolist()

        self.labels = df[LABEL_COLUMNS].values.astype(np.float32)

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):

        text = str(self.texts[idx])

        labels = self.labels[idx]

        encoding = tokenizer(
            text,
            truncation=True,
            padding="max_length",
            max_length=MAX_LEN,
            return_tensors="pt"
        )

        return {
            "input_ids": encoding["input_ids"].squeeze(0),
            "attention_mask": encoding["attention_mask"].squeeze(0),
            "labels": torch.tensor(labels, dtype=torch.float)
        }
train_dataset = EmotionDataset(train_df)

val_dataset = EmotionDataset(val_df)

test_dataset = EmotionDataset(test_df)

In [10]:
train_loader = DataLoader(
    train_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True
)

train_eval_loader = DataLoader(
    train_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False
)

val_loader = DataLoader(
    val_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False
)

test_loader = DataLoader(
    test_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False
)

In [11]:
# pos_weight เดิมทำให้ recall สูง แต่ precision ตกได้
# จึงไม่ fix pos_weight ตายตัว แต่ให้ Optuna tune pos_weight_scale
# scale = 0.0 คือไม่ใช้ pos_weight
# scale = 1.0 คือใช้ pos_weight เต็มสูตร negative / positive

label_counts = train_df[LABEL_COLUMNS].sum().values.astype(np.float32)
total_samples = len(train_df)
neg_counts = total_samples - label_counts

pos_weights_raw = neg_counts / (label_counts + 1e-6)

pos_weights_raw = torch.tensor(
    pos_weights_raw,
    dtype=torch.float
).to(device)

def build_pos_weight(pos_weight_scale):
    pos_weight_scale = float(pos_weight_scale)

    weights = 1.0 + (pos_weights_raw - 1.0) * pos_weight_scale

    return weights.to(device)

print("LABEL COUNTS:", label_counts)
print("RAW POS WEIGHTS:", pos_weights_raw)
print("NO POS WEIGHT:", build_pos_weight(0.0))
print("HALF POS WEIGHT:", build_pos_weight(0.5))

LABEL COUNTS: [ 119. 1320.  218.  328.  112.  212.]
RAW POS WEIGHTS: tensor([13.1176,  0.2727,  6.7064,  4.1220, 14.0000,  6.9245], device='cuda:0')
NO POS WEIGHT: tensor([1., 1., 1., 1., 1., 1.], device='cuda:0')
HALF POS WEIGHT: tensor([7.0588, 0.6364, 3.8532, 2.5610, 7.5000, 3.9623], device='cuda:0')

In [12]:
class AttentionPooling(nn.Module):

    def __init__(self, hidden_size):

        super().__init__()

        self.attention = nn.Sequential(
            nn.Linear(hidden_size, hidden_size),
            nn.Tanh(),
            nn.Linear(hidden_size, 1)
        )

    def forward(self, x, mask):

        scores = self.attention(x).squeeze(-1)

        scores = scores.masked_fill(mask == 0, torch.finfo(scores.dtype).min)

        weights = torch.softmax(scores, dim=1)

        pooled = torch.sum(
            x * weights.unsqueeze(-1),
            dim=1
        )

        return pooled

In [13]:
class EmotionModel(nn.Module):

    def __init__(
        self,
        depth=1,
        heads=2,
        attn_dropout=0.15,
        ff_dropout=0.15,
        ff_mult=2
    ):

        super().__init__()

        self.encoder = AutoModel.from_pretrained(
            MODEL_NAME
        )

        # Fixed Thai encoder: train เฉพาะ decoder + pooling + classifier
        for param in self.encoder.parameters():
            param.requires_grad = False

        hidden_size = self.encoder.config.hidden_size

        self.decoder = Decoder(
            dim=hidden_size,
            depth=depth,
            heads=heads,
            attn_dropout=attn_dropout,
            ff_dropout=ff_dropout,
            ff_mult=ff_mult
        )

        self.pooling = AttentionPooling(hidden_size)

        self.dropout = nn.Dropout(0.30)

        self.fc = nn.Linear(
            hidden_size,
            NUM_LABELS
        )

    def forward(self, input_ids, attention_mask):

        with torch.no_grad():
            outputs = self.encoder(
                input_ids=input_ids,
                attention_mask=attention_mask
            )

        x = outputs.last_hidden_state

        x = self.decoder(x)

        x = self.pooling(x, attention_mask)

        x = self.dropout(x)

        logits = self.fc(x)

        return logits

In [14]:
def optimize_thresholds(
    y_true,
    y_probs,
    min_thr=0.20,
    max_thr=0.80,
    step=0.005
):

    thresholds = np.arange(
        min_thr,
        max_thr + 1e-9,
        step
    )

    best_thresholds = []

    for i in range(NUM_LABELS):

        best_thr = 0.5
        best_score = -1
        best_precision = -1

        true_support = y_true[:, i].sum()

        for thr in thresholds:

            preds = (y_probs[:, i] >= thr).astype(int)

            score = f1_score(
                y_true[:, i],
                preds,
                zero_division=0
            )

            precision = precision_score(
                y_true[:, i],
                preds,
                zero_division=0
            )

            # ถ้า F1 เท่ากัน ให้เลือก threshold ที่ precision สูงกว่า
            # ช่วยแก้ปัญหา optimized เดิมที่ recall สูงแต่ precision ต่ำ
            if (score > best_score) or (
                np.isclose(score, best_score) and precision > best_precision
            ):

                best_score = score
                best_precision = precision
                best_thr = thr

        best_thresholds.append(best_thr)

    return np.array(best_thresholds)

In [15]:
def evaluate(model, loader, thresholds=None):

    model.eval()

    all_labels = []
    all_probs = []

    with torch.no_grad():

        for batch in loader:

            input_ids = batch["input_ids"].to(device)
            attention_mask = batch["attention_mask"].to(device)
            labels = batch["labels"].to(device)

            logits = model(
                input_ids,
                attention_mask
            )

            probs = torch.sigmoid(logits)

            all_probs.append(
                probs.cpu().numpy()
            )

            all_labels.append(
                labels.cpu().numpy()
            )

    all_probs = np.vstack(all_probs)
    all_labels = np.vstack(all_labels)

    if thresholds is None:
        thresholds = np.array([0.5] * NUM_LABELS)

    preds = (all_probs >= thresholds).astype(int)

    micro_f1 = f1_score(
        all_labels,
        preds,
        average="micro",
        zero_division=0
    )

    macro_f1 = f1_score(
        all_labels,
        preds,
        average="macro",
        zero_division=0
    )

    weighted_f1 = f1_score(
        all_labels,
        preds,
        average="weighted",
        zero_division=0
    )

    micro_precision = precision_score(
        all_labels,
        preds,
        average="micro",
        zero_division=0
    )

    macro_precision = precision_score(
        all_labels,
        preds,
        average="macro",
        zero_division=0
    )

    micro_recall = recall_score(
        all_labels,
        preds,
        average="micro",
        zero_division=0
    )

    macro_recall = recall_score(
        all_labels,
        preds,
        average="macro",
        zero_division=0
    )

    per_label_f1 = f1_score(
        all_labels,
        preds,
        average=None,
        zero_division=0
    )

    per_label_precision = precision_score(
        all_labels,
        preds,
        average=None,
        zero_division=0
    )

    per_label_recall = recall_score(
        all_labels,
        preds,
        average=None,
        zero_division=0
    )

    subset_accuracy = accuracy_score(
        all_labels,
        preds
    )

    h_loss = hamming_loss(
        all_labels,
        preds
    )

    return {
        "micro_f1": micro_f1,
        "macro_f1": macro_f1,
        "weighted_f1": weighted_f1,
        "micro_precision": micro_precision,
        "macro_precision": macro_precision,
        "micro_recall": micro_recall,
        "macro_recall": macro_recall,
        "per_label_f1": per_label_f1,
        "per_label_precision": per_label_precision,
        "per_label_recall": per_label_recall,
        "min_per_label_f1": float(np.min(per_label_f1)),
        "accuracy": subset_accuracy,
        "subset_accuracy": subset_accuracy,
        "hamming_loss": h_loss,
        "labels": all_labels,
        "preds": preds,
        "probs": all_probs
    }


def objective_score(result):
    # objective ใหม่:
    # - macro_f1 สำคัญที่สุด เพราะต้องชนะราย class
    # - micro_f1 ยังสำคัญ
    # - min_per_label_f1 กันไม่ให้ class ใด class หนึ่งต่ำ โดยเฉพาะ Disgust
    # - subset accuracy ช่วยให้ทายชุด label ตรงขึ้น
    return (
        0.45 * result["macro_f1"]
        + 0.25 * result["micro_f1"]
        + 0.20 * result["min_per_label_f1"]
        + 0.10 * result["subset_accuracy"]
    )

In [16]:
def train_model(
    model,
    train_loader,
    val_loader,
    lr,
    weight_decay,
    epochs=None,
    pos_weight_scale=0.0,
    label_smoothing=0.0,
    loss_name="bce",
    focal_gamma=2.0,
    verbose=True
):

    if epochs is None:
        epochs = EPOCHS

    pos_weight = build_pos_weight(pos_weight_scale)

    bce_loss = nn.BCEWithLogitsLoss(
        pos_weight=pos_weight,
        reduction="none"
    )

    trainable_params = [p for p in model.parameters() if p.requires_grad]

    optimizer = torch.optim.AdamW(
        trainable_params,
        lr=lr,
        weight_decay=weight_decay
    )

    total_steps = len(train_loader) * epochs

    scheduler = get_linear_schedule_with_warmup(
        optimizer,
        num_warmup_steps=int(0.06 * total_steps),
        num_training_steps=total_steps
    )

    use_amp = device.type == "cuda"

    scaler = torch.cuda.amp.GradScaler(
        enabled=use_amp
    )

    for epoch in range(epochs):

        model.train()
        total_loss = 0

        loop = tqdm(
            train_loader,
            disable=not verbose
        )

        for batch in loop:

            input_ids = batch["input_ids"].to(device)
            attention_mask = batch["attention_mask"].to(device)
            labels = batch["labels"].to(device)

            if label_smoothing > 0:
                # smooth toward 0.5 for multi-label BCE
                labels_for_loss = labels * (1.0 - label_smoothing) + 0.5 * label_smoothing
            else:
                labels_for_loss = labels

            optimizer.zero_grad()

            with torch.cuda.amp.autocast(enabled=use_amp):

                logits = model(
                    input_ids,
                    attention_mask
                )

                loss_matrix = bce_loss(
                    logits,
                    labels_for_loss
                )

                if loss_name == "focal":
                    probs = torch.sigmoid(logits)
                    pt = probs * labels + (1 - probs) * (1 - labels)
                    focal_weight = (1 - pt).pow(focal_gamma)
                    loss = (focal_weight * loss_matrix).mean()
                else:
                    loss = loss_matrix.mean()

            scaler.scale(loss).backward()

            torch.nn.utils.clip_grad_norm_(
                trainable_params,
                1.0
            )

            scaler.step(optimizer)
            scaler.update()
            scheduler.step()

            total_loss += loss.item()

            if verbose:
                loop.set_description(
                    f"Epoch {epoch+1}/{epochs}"
                )

                loop.set_postfix(
                    loss=loss.item()
                )

        if verbose:

            val_raw = evaluate(
                model,
                val_loader
            )

            val_thresholds = optimize_thresholds(
                val_raw["labels"],
                val_raw["probs"]
            )

            val_result = evaluate(
                model,
                val_loader,
                val_thresholds
            )

            print("\n======================")
            print(f"Epoch {epoch+1}")
            print("======================")

            print(
                f"VAL SUBSET ACC : {val_result['subset_accuracy']:.4f}"
            )

            print(
                f"VAL MICRO P/R/F1: "
                f"{val_result['micro_precision']:.4f} / "
                f"{val_result['micro_recall']:.4f} / "
                f"{val_result['micro_f1']:.4f}"
            )

            print(
                f"VAL MACRO P/R/F1: "
                f"{val_result['macro_precision']:.4f} / "
                f"{val_result['macro_recall']:.4f} / "
                f"{val_result['macro_f1']:.4f}"
            )

            print(
                f"VAL MIN LABEL F1: {val_result['min_per_label_f1']:.4f}"
            )

            print(
                f"VAL WEIGHTED F1: {val_result['weighted_f1']:.4f}"
            )

            print(
                f"VAL HAMMING LOSS: {val_result['hamming_loss']:.4f}"
            )

    return model

In [17]:
def objective(trial):

    # baseline trial จะถูก enqueue ไว้ก่อนหน้า
    depth = trial.suggest_int(
        "depth",
        1,
        3
    )

    heads = trial.suggest_categorical(
        "heads",
        [2, 4, 8]
    )

    # ลด dropout range จากเดิมที่สูงเกินไป เพราะเดิม optimized มีแนวโน้ม underfit / recall เยอะ precision ตก
    attn_dropout = trial.suggest_float(
        "attn_dropout",
        0.05,
        0.30
    )

    ff_dropout = trial.suggest_float(
        "ff_dropout",
        0.05,
        0.30
    )

    ff_mult = trial.suggest_int(
        "ff_mult",
        2,
        4
    )

    lr = trial.suggest_float(
        "lr",
        1e-5,
        1e-4,
        log=True
    )

    weight_decay = trial.suggest_float(
        "weight_decay",
        1e-6,
        5e-3,
        log=True
    )

    # จุดสำคัญ: ให้ Optuna เลือกว่าจะใช้ pos_weight แค่ไหน
    # ถ้า scale สูงเกินจะ recall สูงแต่ precision ลด
    pos_weight_scale = trial.suggest_float(
        "pos_weight_scale",
        0.0,
        0.60
    )

    label_smoothing = trial.suggest_float(
        "label_smoothing",
        0.0,
        0.04
    )

    loss_name = trial.suggest_categorical(
        "loss_name",
        ["bce", "focal"]
    )

    focal_gamma = trial.suggest_float(
        "focal_gamma",
        1.0,
        2.5
    )

    model = EmotionModel(
        depth=depth,
        heads=heads,
        attn_dropout=attn_dropout,
        ff_dropout=ff_dropout,
        ff_mult=ff_mult
    ).to(device)

    model = train_model(
        model,
        train_loader,
        val_loader,
        lr=lr,
        weight_decay=weight_decay,
        epochs=OPTUNA_EPOCHS,
        pos_weight_scale=pos_weight_scale,
        label_smoothing=label_smoothing,
        loss_name=loss_name,
        focal_gamma=focal_gamma,
        verbose=False
    )

    val_raw = evaluate(
        model,
        val_loader
    )

    thresholds = optimize_thresholds(
        val_raw["labels"],
        val_raw["probs"]
    )

    val_result = evaluate(
        model,
        val_loader,
        thresholds
    )

    score = objective_score(val_result)

    trial.set_user_attr("val_macro_f1", float(val_result["macro_f1"]))
    trial.set_user_attr("val_micro_f1", float(val_result["micro_f1"]))
    trial.set_user_attr("val_min_per_label_f1", float(val_result["min_per_label_f1"]))
    trial.set_user_attr("val_subset_accuracy", float(val_result["subset_accuracy"]))
    trial.set_user_attr("thresholds", thresholds.tolist())

    return score

In [18]:
sampler = optuna.samplers.TPESampler(
    seed=SEED,
    multivariate=True
)

study = optuna.create_study(
    direction="maximize",
    sampler=sampler
)

# ใส่ค่า baseline/non-optimized configuration เป็น trial แรก
# เพื่อให้ optimization มีจุดเริ่มต้นที่ไม่แพ้ baseline ง่าย ๆ
study.enqueue_trial({
    "depth": 1,
    "heads": 2,
    "attn_dropout": 0.20,
    "ff_dropout": 0.20,
    "ff_mult": 2,
    "lr": 2e-5,
    "weight_decay": 1e-2,
    "pos_weight_scale": 0.0,
    "label_smoothing": 0.0,
    "loss_name": "bce",
    "focal_gamma": 2.0
})

study.optimize(
    objective,
    n_trials=N_TRIALS
)

[I 2026-09-27 04:18:19,681] A new study created in memory with name: no-name-229eeb99-59f9-4906-99e8-079b91ee396f

model.safetensors:   0%|          | 0.00/714M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: bert-base-multilingual-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
[I 2026-09-27 04:21:00,761] Trial 0 finished with value: 0.32237267026074146 and parameters: {'depth': 1, 'heads': 2, 'attn_dropout': 0.2, 'ff_dropout': 0.2, 'ff_mult': 2, 'lr': 2e-05, 'weight_decay': 0.01, 'pos_weight_scale': 0.0, 'label_smoothing': 0.0, 'loss_name': 'bce', 'focal_gamma': 2.0}. Best is trial 0 with value: 0.32237267026074146.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: bert-base-multilingual-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
[I 2026-09-27 04:23:58,278] Trial 1 finished with value: 0.43354057186037087 and parameters: {'depth': 2, 'heads': 2, 'attn_dropout': 0.08900466011060913, 'ff_dropout': 0.08899863008405066, 'ff_mult': 2, 'lr': 7.348118405270451e-05, 'weight_decay': 0.00016730402817820238, 'pos_weight_scale': 0.4248435466776273, 'label_smoothing': 0.0008233797718320979, 'loss_name': 'bce', 'focal_gamma': 1.3185086660174141}. Best is trial 1 with value: 0.43354057186037087.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: bert-base-multilingual-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
[I 2026-09-27 04:26:50,186] Trial 2 finished with value: 0.3659314697237662 and parameters: {'depth': 1, 'heads': 8, 'attn_dropout': 0.15798625466052896, 'ff_dropout': 0.12280728504951048, 'ff_mult': 3, 'lr': 1.378776461935377e-05, 'weight_decay': 1.2040216379191716e-05, 'pos_weight_scale': 0.219817105976215, 'label_smoothing': 0.018242799368681437, 'loss_name': 'bce', 'focal_gamma': 1.7713516576204174}. Best is trial 1 with value: 0.43354057186037087.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: bert-base-multilingual-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
[I 2026-09-27 04:30:08,595] Trial 3 finished with value: 0.44088675553799417 and parameters: {'depth': 2, 'heads': 4, 'attn_dropout': 0.06626289824631988, 'ff_dropout': 0.2872213843133333, 'ff_mult': 4, 'lr': 6.432759992849896e-05, 'weight_decay': 1.3389279116695482e-05, 'pos_weight_scale': 0.058603268403830316, 'label_smoothing': 0.027369321060486278, 'loss_name': 'bce', 'focal_gamma': 1.7427653651669053}. Best is trial 3 with value: 0.44088675553799417.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: bert-base-multilingual-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
[I 2026-09-27 04:32:53,181] Trial 4 finished with value: 0.3807351339507308 and parameters: {'depth': 1, 'heads': 2, 'attn_dropout': 0.12792776902235276, 'ff_dropout': 0.1800170052944527, 'ff_mult': 3, 'lr': 1.5305744365500174e-05, 'weight_decay': 0.0038589082671053863, 'pos_weight_scale': 0.4650796940166687, 'label_smoothing': 0.03757995766256757, 'loss_name': 'bce', 'focal_gamma': 2.3828113525346755}. Best is trial 3 with value: 0.44088675553799417.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: bert-base-multilingual-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
[I 2026-09-27 04:35:49,740] Trial 5 finished with value: 0.40208204508522605 and parameters: {'depth': 1, 'heads': 8, 'attn_dropout': 0.14716932242237052, 'ff_dropout': 0.11783725794347398, 'ff_mult': 4, 'lr': 2.2738055735631803e-05, 'weight_decay': 1.0943804457233499e-05, 'pos_weight_scale': 0.32561764989494907, 'label_smoothing': 0.005636968998990506, 'loss_name': 'bce', 'focal_gamma': 2.480330404900776}. Best is trial 3 with value: 0.44088675553799417.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: bert-base-multilingual-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
[I 2026-09-27 04:39:49,903] Trial 6 finished with value: 0.3858487413219332 and parameters: {'depth': 3, 'heads': 8, 'attn_dropout': 0.22671433596190427, 'ff_dropout': 0.23225179201024682, 'ff_mult': 4, 'lr': 1.1858906685575266e-05, 'weight_decay': 2.118136662725141e-05, 'pos_weight_scale': 0.06952143571507782, 'label_smoothing': 0.034524137035023744, 'loss_name': 'bce', 'focal_gamma': 1.0953375254290354}. Best is trial 3 with value: 0.44088675553799417.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: bert-base-multilingual-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
[I 2026-09-27 04:42:34,019] Trial 7 finished with value: 0.4160639328314938 and parameters: {'depth': 1, 'heads': 4, 'attn_dropout': 0.2718031856440816, 'ff_dropout': 0.16805373129048734, 'ff_mult': 2, 'lr': 5.1670752600232777e-05, 'weight_decay': 0.0006518100832986183, 'pos_weight_scale': 0.33676631854169775, 'label_smoothing': 0.03083868719818244, 'loss_name': 'focal', 'focal_gamma': 1.6413115275378245}. Best is trial 3 with value: 0.44088675553799417.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: bert-base-multilingual-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
[I 2026-09-27 04:45:31,133] Trial 8 finished with value: 0.40606456369923943 and parameters: {'depth': 1, 'heads': 8, 'attn_dropout': 0.12858899526908169, 'ff_dropout': 0.17714267279117568, 'ff_mult': 4, 'lr': 1.775383703652225e-05, 'weight_decay': 3.29605251529397e-05, 'pos_weight_scale': 0.4533306831258292, 'label_smoothing': 0.009151926619664899, 'loss_name': 'focal', 'focal_gamma': 1.2418319308810066}. Best is trial 3 with value: 0.44088675553799417.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: bert-base-multilingual-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
[I 2026-09-27 04:49:31,060] Trial 9 finished with value: 0.43012581358850827 and parameters: {'depth': 3, 'heads': 8, 'attn_dropout': 0.25091801922477863, 'ff_dropout': 0.09664251472150896, 'ff_mult': 4, 'lr': 3.4621209972935956e-05, 'weight_decay': 0.0009698329033198108, 'pos_weight_scale': 0.5376547799540959, 'label_smoothing': 0.012720138998874555, 'loss_name': 'focal', 'focal_gamma': 1.6406616829393845}. Best is trial 3 with value: 0.44088675553799417.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: bert-base-multilingual-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
[I 2026-09-27 04:52:49,792] Trial 10 finished with value: 0.4225197436946073 and parameters: {'depth': 2, 'heads': 4, 'attn_dropout': 0.09363033344036667, 'ff_dropout': 0.27869572865739967, 'ff_mult': 4, 'lr': 2.1207276043507604e-05, 'weight_decay': 0.00019832119872655304, 'pos_weight_scale': 0.1339097440884836, 'label_smoothing': 0.03582429738562117, 'loss_name': 'bce', 'focal_gamma': 1.9055750428119642}. Best is trial 3 with value: 0.44088675553799417.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: bert-base-multilingual-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
[I 2026-09-27 04:56:56,855] Trial 11 finished with value: 0.43022162304293743 and parameters: {'depth': 3, 'heads': 4, 'attn_dropout': 0.08700383318399307, 'ff_dropout': 0.2602780174964446, 'ff_mult': 4, 'lr': 7.068080767665572e-05, 'weight_decay': 1.303976167919204e-06, 'pos_weight_scale': 0.14163829133081907, 'label_smoothing': 0.03608913520667696, 'loss_name': 'bce', 'focal_gamma': 1.8806583707778441}. Best is trial 3 with value: 0.44088675553799417.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: bert-base-multilingual-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
[I 2026-09-27 04:59:41,846] Trial 12 finished with value: 0.4279456479267566 and parameters: {'depth': 1, 'heads': 2, 'attn_dropout': 0.07210552560334901, 'ff_dropout': 0.06617170240079565, 'ff_mult': 3, 'lr': 8.659079358666528e-05, 'weight_decay': 0.00016663144899102625, 'pos_weight_scale': 0.4289943513452733, 'label_smoothing': 0.0020519398763986126, 'loss_name': 'bce', 'focal_gamma': 1.6461103339038075}. Best is trial 3 with value: 0.44088675553799417.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: bert-base-multilingual-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
[I 2026-09-27 05:02:57,432] Trial 13 finished with value: 0.411627125745026 and parameters: {'depth': 3, 'heads': 2, 'attn_dropout': 0.17955836014446094, 'ff_dropout': 0.06210323804852701, 'ff_mult': 2, 'lr': 6.908221743489177e-05, 'weight_decay': 0.00023444261445572614, 'pos_weight_scale': 0.4288288564429932, 'label_smoothing': 0.0014767172620863951, 'loss_name': 'bce', 'focal_gamma': 1.5145074593922525}. Best is trial 3 with value: 0.44088675553799417.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: bert-base-multilingual-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
[I 2026-09-27 05:05:49,162] Trial 14 finished with value: 0.36161485141310484 and parameters: {'depth': 1, 'heads': 4, 'attn_dropout': 0.11666808695977993, 'ff_dropout': 0.25889415365772783, 'ff_mult': 4, 'lr': 4.599070448088427e-05, 'weight_decay': 1.0495812455777918e-06, 'pos_weight_scale': 0.009586371114677937, 'label_smoothing': 0.02580880884430322, 'loss_name': 'bce', 'focal_gamma': 1.7935706162351548}. Best is trial 3 with value: 0.44088675553799417.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: bert-base-multilingual-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
[I 2026-09-27 05:09:00,442] Trial 15 finished with value: 0.457343052164132 and parameters: {'depth': 2, 'heads': 4, 'attn_dropout': 0.07444441148051117, 'ff_dropout': 0.28742458640029656, 'ff_mult': 3, 'lr': 7.862432786122375e-05, 'weight_decay': 4.8478296895945165e-05, 'pos_weight_scale': 0.03725963643713588, 'label_smoothing': 0.031991100267631474, 'loss_name': 'bce', 'focal_gamma': 1.2189120179762392}. Best is trial 15 with value: 0.457343052164132.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: bert-base-multilingual-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
[I 2026-09-27 05:12:50,058] Trial 16 finished with value: 0.456447885591052 and parameters: {'depth': 3, 'heads': 8, 'attn_dropout': 0.08640154099189082, 'ff_dropout': 0.2873264191496316, 'ff_mult': 3, 'lr': 5.015004832740941e-05, 'weight_decay': 0.0014297601270751128, 'pos_weight_scale': 0.06188820947964724, 'label_smoothing': 0.035211502177202, 'loss_name': 'bce', 'focal_gamma': 1.3929668909262014}. Best is trial 15 with value: 0.457343052164132.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: bert-base-multilingual-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
[I 2026-09-27 05:16:39,214] Trial 17 finished with value: 0.4267629063077124 and parameters: {'depth': 3, 'heads': 8, 'attn_dropout': 0.1184139621689711, 'ff_dropout': 0.24968109246761716, 'ff_mult': 3, 'lr': 6.821756176353214e-05, 'weight_decay': 0.0006224510470954487, 'pos_weight_scale': 0.15864902027169775, 'label_smoothing': 0.03690714862807998, 'loss_name': 'bce', 'focal_gamma': 1.6095169970594356}. Best is trial 15 with value: 0.457343052164132.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: bert-base-multilingual-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
[I 2026-09-27 05:19:43,259] Trial 18 finished with value: 0.44007255673337736 and parameters: {'depth': 2, 'heads': 4, 'attn_dropout': 0.08600378661049056, 'ff_dropout': 0.28480834857812715, 'ff_mult': 2, 'lr': 7.96547113406551e-05, 'weight_decay': 0.00013393110702110043, 'pos_weight_scale': 0.01670706035321594, 'label_smoothing': 0.03813172401416212, 'loss_name': 'focal', 'focal_gamma': 1.1489573400505673}. Best is trial 15 with value: 0.457343052164132.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: bert-base-multilingual-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
[I 2026-09-27 05:22:36,210] Trial 19 finished with value: 0.40851828833545534 and parameters: {'depth': 1, 'heads': 8, 'attn_dropout': 0.08511840666433054, 'ff_dropout': 0.1730310028549375, 'ff_mult': 3, 'lr': 5.6586638769682436e-05, 'weight_decay': 5.042650713129243e-05, 'pos_weight_scale': 0.04345994675480756, 'label_smoothing': 0.029752929807961334, 'loss_name': 'bce', 'focal_gamma': 1.0389752614986352}. Best is trial 15 with value: 0.457343052164132.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: bert-base-multilingual-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
[I 2026-09-27 05:25:59,512] Trial 20 finished with value: 0.42964000744534747 and parameters: {'depth': 3, 'heads': 4, 'attn_dropout': 0.1301447470270796, 'ff_dropout': 0.26996892311866716, 'ff_mult': 2, 'lr': 9.765212042187263e-05, 'weight_decay': 1.491012355222318e-05, 'pos_weight_scale': 0.06137228930272977, 'label_smoothing': 0.025156892742476802, 'loss_name': 'bce', 'focal_gamma': 1.2812057317943346}. Best is trial 15 with value: 0.457343052164132.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: bert-base-multilingual-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
[I 2026-09-27 05:29:19,124] Trial 21 finished with value: 0.44202729546173547 and parameters: {'depth': 2, 'heads': 4, 'attn_dropout': 0.08720560817781038, 'ff_dropout': 0.27900395914210385, 'ff_mult': 4, 'lr': 8.835029540470434e-05, 'weight_decay': 0.0006782670943759952, 'pos_weight_scale': 0.11423506835262899, 'label_smoothing': 0.01647853073700497, 'loss_name': 'bce', 'focal_gamma': 1.547489105215796}. Best is trial 15 with value: 0.457343052164132.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: bert-base-multilingual-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
[I 2026-09-27 05:33:05,453] Trial 22 finished with value: 0.4236788676542912 and parameters: {'depth': 3, 'heads': 4, 'attn_dropout': 0.0875269347705505, 'ff_dropout': 0.23997600724324503, 'ff_mult': 4, 'lr': 4.5685122594348024e-05, 'weight_decay': 0.0007500390594071634, 'pos_weight_scale': 0.2711299280549061, 'label_smoothing': 0.016867489222404476, 'loss_name': 'bce', 'focal_gamma': 1.4503270882276853}. Best is trial 15 with value: 0.457343052164132.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: bert-base-multilingual-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
[I 2026-09-27 05:35:56,852] Trial 23 finished with value: 0.4097051254301341 and parameters: {'depth': 1, 'heads': 4, 'attn_dropout': 0.06008228300637698, 'ff_dropout': 0.28506942630754145, 'ff_mult': 4, 'lr': 6.391363322213464e-05, 'weight_decay': 0.002644682509701044, 'pos_weight_scale': 0.018750903320745888, 'label_smoothing': 0.002080151085856895, 'loss_name': 'focal', 'focal_gamma': 1.4871568225082585}. Best is trial 15 with value: 0.457343052164132.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: bert-base-multilingual-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
[I 2026-09-27 05:39:25,387] Trial 24 finished with value: 0.44349664626640317 and parameters: {'depth': 2, 'heads': 8, 'attn_dropout': 0.0861380700059587, 'ff_dropout': 0.24556596787956292, 'ff_mult': 4, 'lr': 6.408638331804635e-05, 'weight_decay': 0.0008555714412500243, 'pos_weight_scale': 0.021220462502880608, 'label_smoothing': 0.012931370888675915, 'loss_name': 'bce', 'focal_gamma': 1.6229035389652218}. Best is trial 15 with value: 0.457343052164132.

In [19]:
print("\n======================")
print("BEST PARAMETERS")
print("======================")

print(study.best_params)

print("\n======================")
print("BEST TRIAL VALIDATION ATTRS")
print("======================")

print("objective_score:", study.best_value)
print("val_macro_f1:", study.best_trial.user_attrs.get("val_macro_f1"))
print("val_micro_f1:", study.best_trial.user_attrs.get("val_micro_f1"))
print("val_min_per_label_f1:", study.best_trial.user_attrs.get("val_min_per_label_f1"))
print("val_subset_accuracy:", study.best_trial.user_attrs.get("val_subset_accuracy"))

best_params = study.best_params

======================
BEST PARAMETERS
======================
{'depth': 2, 'heads': 4, 'attn_dropout': 0.07444441148051117, 'ff_dropout': 0.28742458640029656, 'ff_mult': 3, 'lr': 7.862432786122375e-05, 'weight_decay': 4.8478296895945165e-05, 'pos_weight_scale': 0.03725963643713588, 'label_smoothing': 0.031991100267631474, 'loss_name': 'bce', 'focal_gamma': 1.2189120179762392}

======================
BEST TRIAL VALIDATION ATTRS
======================
objective_score: 0.457343052164132
val_macro_f1: 0.44231987466662326
val_micro_f1: 0.6743075453677173
val_min_per_label_f1: 0.25
val_subset_accuracy: 0.3972222222222222

In [20]:
final_model = EmotionModel(
    depth=best_params["depth"],
    heads=best_params["heads"],
    attn_dropout=best_params["attn_dropout"],
    ff_dropout=best_params["ff_dropout"],
    ff_mult=best_params["ff_mult"]
).to(device)

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: bert-base-multilingual-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [21]:
final_model = train_model(
    final_model,
    train_loader,
    val_loader,
    lr=best_params["lr"],
    weight_decay=best_params["weight_decay"],
    epochs=EPOCHS,
    pos_weight_scale=best_params["pos_weight_scale"],
    label_smoothing=best_params["label_smoothing"],
    loss_name=best_params["loss_name"],
    focal_gamma=best_params["focal_gamma"],
    verbose=True
)

Epoch 1/100: 100%|██████████| 27/27 [00:05<00:00,  5.17it/s, loss=0.581]

======================
Epoch 1
======================
VAL SUBSET ACC : 0.0000
VAL MICRO P/R/F1: 0.2738 / 0.9008 / 0.4200
VAL MACRO P/R/F1: 0.2558 / 0.8071 / 0.3388
VAL MIN LABEL F1: 0.1250
VAL WEIGHTED F1: 0.6100
VAL HAMMING LOSS: 0.5690

Epoch 2/100: 100%|██████████| 27/27 [00:05<00:00,  5.11it/s, loss=0.542]

======================
Epoch 2
======================
VAL SUBSET ACC : 0.4000
VAL MICRO P/R/F1: 0.7178 / 0.5870 / 0.6459
VAL MACRO P/R/F1: 0.1616 / 0.1866 / 0.1709
VAL MIN LABEL F1: 0.0000
VAL WEIGHTED F1: 0.5226
VAL HAMMING LOSS: 0.1472

Epoch 3/100: 100%|██████████| 27/27 [00:05<00:00,  5.10it/s, loss=0.427]

======================
Epoch 3
======================
VAL SUBSET ACC : 0.2667
VAL MICRO P/R/F1: 0.5291 / 0.6984 / 0.6021
VAL MACRO P/R/F1: 0.3883 / 0.3473 / 0.2713
VAL MIN LABEL F1: 0.0000
VAL WEIGHTED F1: 0.5833
VAL HAMMING LOSS: 0.2111

Epoch 4/100: 100%|██████████| 27/27 [00:05<00:00,  5.07it/s, loss=0.516]

======================
Epoch 4
======================
VAL SUBSET ACC : 0.3222
VAL MICRO P/R/F1: 0.5733 / 0.6964 / 0.6289
VAL MACRO P/R/F1: 0.3677 / 0.3488 / 0.3032
VAL MIN LABEL F1: 0.0000
VAL WEIGHTED F1: 0.6030
VAL HAMMING LOSS: 0.1880

Epoch 5/100: 100%|██████████| 27/27 [00:05<00:00,  5.07it/s, loss=0.499]

======================
Epoch 5
======================
VAL SUBSET ACC : 0.4056
VAL MICRO P/R/F1: 0.6619 / 0.6619 / 0.6619
VAL MACRO P/R/F1: 0.4025 / 0.3066 / 0.3092
VAL MIN LABEL F1: 0.0000
VAL WEIGHTED F1: 0.6083
VAL HAMMING LOSS: 0.1546

Epoch 6/100: 100%|██████████| 27/27 [00:05<00:00,  5.12it/s, loss=0.48]

======================
Epoch 6
======================
VAL SUBSET ACC : 0.2889
VAL MICRO P/R/F1: 0.5190 / 0.7470 / 0.6124
VAL MACRO P/R/F1: 0.3464 / 0.4311 / 0.3322
VAL MIN LABEL F1: 0.0000
VAL WEIGHTED F1: 0.6200
VAL HAMMING LOSS: 0.2162

Epoch 7/100: 100%|██████████| 27/27 [00:05<00:00,  5.11it/s, loss=0.412]

======================
Epoch 7
======================
VAL SUBSET ACC : 0.4000
VAL MICRO P/R/F1: 0.6486 / 0.6802 / 0.6640
VAL MACRO P/R/F1: 0.4598 / 0.3362 / 0.3342
VAL MIN LABEL F1: 0.0000
VAL WEIGHTED F1: 0.6199
VAL HAMMING LOSS: 0.1574

Epoch 8/100: 100%|██████████| 27/27 [00:05<00:00,  5.12it/s, loss=0.363]

======================
Epoch 8
======================
VAL SUBSET ACC : 0.3694
VAL MICRO P/R/F1: 0.6077 / 0.7024 / 0.6516
VAL MACRO P/R/F1: 0.3716 / 0.3689 / 0.3240
VAL MIN LABEL F1: 0.0000
VAL WEIGHTED F1: 0.6102
VAL HAMMING LOSS: 0.1718

Epoch 9/100: 100%|██████████| 27/27 [00:05<00:00,  5.11it/s, loss=0.497]

======================
Epoch 9
======================
VAL SUBSET ACC : 0.3444
VAL MICRO P/R/F1: 0.5778 / 0.7368 / 0.6477
VAL MACRO P/R/F1: 0.4034 / 0.4308 / 0.3776
VAL MIN LABEL F1: 0.0000
VAL WEIGHTED F1: 0.6416
VAL HAMMING LOSS: 0.1833

Epoch 10/100: 100%|██████████| 27/27 [00:05<00:00,  5.09it/s, loss=0.589]

======================
Epoch 10
======================
VAL SUBSET ACC : 0.3667
VAL MICRO P/R/F1: 0.6338 / 0.6903 / 0.6609
VAL MACRO P/R/F1: 0.3902 / 0.3883 / 0.3774
VAL MIN LABEL F1: 0.0000
VAL WEIGHTED F1: 0.6395
VAL HAMMING LOSS: 0.1620

Epoch 11/100: 100%|██████████| 27/27 [00:05<00:00,  5.11it/s, loss=0.342]

======================
Epoch 11
======================
VAL SUBSET ACC : 0.3611
VAL MICRO P/R/F1: 0.6147 / 0.7105 / 0.6592
VAL MACRO P/R/F1: 0.4093 / 0.4069 / 0.3798
VAL MIN LABEL F1: 0.0606
VAL WEIGHTED F1: 0.6417
VAL HAMMING LOSS: 0.1681

Epoch 12/100: 100%|██████████| 27/27 [00:05<00:00,  5.13it/s, loss=0.384]

======================
Epoch 12
======================
VAL SUBSET ACC : 0.3750
VAL MICRO P/R/F1: 0.6362 / 0.6903 / 0.6621
VAL MACRO P/R/F1: 0.4285 / 0.3828 / 0.3828
VAL MIN LABEL F1: 0.1212
VAL WEIGHTED F1: 0.6354
VAL HAMMING LOSS: 0.1611

Epoch 13/100: 100%|██████████| 27/27 [00:05<00:00,  5.13it/s, loss=0.386]

======================
Epoch 13
======================
VAL SUBSET ACC : 0.3833
VAL MICRO P/R/F1: 0.6270 / 0.7247 / 0.6723
VAL MACRO P/R/F1: 0.4651 / 0.4460 / 0.4278
VAL MIN LABEL F1: 0.1714
VAL WEIGHTED F1: 0.6631
VAL HAMMING LOSS: 0.1616

Epoch 14/100: 100%|██████████| 27/27 [00:05<00:00,  5.08it/s, loss=0.375]

======================
Epoch 14
======================
VAL SUBSET ACC : 0.3278
VAL MICRO P/R/F1: 0.5869 / 0.7449 / 0.6566
VAL MACRO P/R/F1: 0.4383 / 0.4597 / 0.4090
VAL MIN LABEL F1: 0.1290
VAL WEIGHTED F1: 0.6565
VAL HAMMING LOSS: 0.1782

Epoch 15/100: 100%|██████████| 27/27 [00:05<00:00,  5.11it/s, loss=0.478]

======================
Epoch 15
======================
VAL SUBSET ACC : 0.3556
VAL MICRO P/R/F1: 0.6013 / 0.7267 / 0.6581
VAL MACRO P/R/F1: 0.4005 / 0.4574 / 0.4117
VAL MIN LABEL F1: 0.1212
VAL WEIGHTED F1: 0.6576
VAL HAMMING LOSS: 0.1727

Epoch 16/100: 100%|██████████| 27/27 [00:05<00:00,  5.12it/s, loss=0.405]

======================
Epoch 16
======================
VAL SUBSET ACC : 0.3972
VAL MICRO P/R/F1: 0.6511 / 0.6761 / 0.6634
VAL MACRO P/R/F1: 0.4047 / 0.3791 / 0.3832
VAL MIN LABEL F1: 0.1765
VAL WEIGHTED F1: 0.6354
VAL HAMMING LOSS: 0.1569

Epoch 17/100: 100%|██████████| 27/27 [00:05<00:00,  5.12it/s, loss=0.339]

======================
Epoch 17
======================
VAL SUBSET ACC : 0.3361
VAL MICRO P/R/F1: 0.5849 / 0.7672 / 0.6637
VAL MACRO P/R/F1: 0.4370 / 0.5154 / 0.4481
VAL MIN LABEL F1: 0.1818
VAL WEIGHTED F1: 0.6760
VAL HAMMING LOSS: 0.1778

Epoch 18/100: 100%|██████████| 27/27 [00:05<00:00,  5.11it/s, loss=0.307]

======================
Epoch 18
======================
VAL SUBSET ACC : 0.3722
VAL MICRO P/R/F1: 0.6355 / 0.7024 / 0.6673
VAL MACRO P/R/F1: 0.4261 / 0.4190 / 0.4130
VAL MIN LABEL F1: 0.1714
VAL WEIGHTED F1: 0.6540
VAL HAMMING LOSS: 0.1602

Epoch 19/100: 100%|██████████| 27/27 [00:05<00:00,  5.11it/s, loss=0.407]

======================
Epoch 19
======================
VAL SUBSET ACC : 0.3778
VAL MICRO P/R/F1: 0.6417 / 0.7105 / 0.6744
VAL MACRO P/R/F1: 0.4172 / 0.4310 / 0.4198
VAL MIN LABEL F1: 0.1500
VAL WEIGHTED F1: 0.6615
VAL HAMMING LOSS: 0.1569

Epoch 20/100: 100%|██████████| 27/27 [00:05<00:00,  5.06it/s, loss=0.403]

======================
Epoch 20
======================
VAL SUBSET ACC : 0.4500
VAL MICRO P/R/F1: 0.7100 / 0.6640 / 0.6862
VAL MACRO P/R/F1: 0.4977 / 0.3553 / 0.3708
VAL MIN LABEL F1: 0.0769
VAL WEIGHTED F1: 0.6285
VAL HAMMING LOSS: 0.1389

Epoch 21/100: 100%|██████████| 27/27 [00:05<00:00,  5.10it/s, loss=0.421]

======================
Epoch 21
======================
VAL SUBSET ACC : 0.3861
VAL MICRO P/R/F1: 0.6442 / 0.7146 / 0.6775
VAL MACRO P/R/F1: 0.4601 / 0.4201 / 0.4073
VAL MIN LABEL F1: 0.0741
VAL WEIGHTED F1: 0.6593
VAL HAMMING LOSS: 0.1556

Epoch 22/100: 100%|██████████| 27/27 [00:05<00:00,  5.11it/s, loss=0.261]

======================
Epoch 22
======================
VAL SUBSET ACC : 0.3500
VAL MICRO P/R/F1: 0.6124 / 0.7389 / 0.6697
VAL MACRO P/R/F1: 0.4268 / 0.4778 / 0.4365
VAL MIN LABEL F1: 0.1818
VAL WEIGHTED F1: 0.6703
VAL HAMMING LOSS: 0.1667

Epoch 23/100: 100%|██████████| 27/27 [00:05<00:00,  5.13it/s, loss=0.426]

======================
Epoch 23
======================
VAL SUBSET ACC : 0.3528
VAL MICRO P/R/F1: 0.6158 / 0.7105 / 0.6598
VAL MACRO P/R/F1: 0.4337 / 0.4377 / 0.4167
VAL MIN LABEL F1: 0.2273
VAL WEIGHTED F1: 0.6559
VAL HAMMING LOSS: 0.1676

Epoch 24/100: 100%|██████████| 27/27 [00:05<00:00,  5.13it/s, loss=0.407]

======================
Epoch 24
======================
VAL SUBSET ACC : 0.3389
VAL MICRO P/R/F1: 0.5948 / 0.7429 / 0.6607
VAL MACRO P/R/F1: 0.4156 / 0.4942 / 0.4378
VAL MIN LABEL F1: 0.2105
VAL WEIGHTED F1: 0.6700
VAL HAMMING LOSS: 0.1745

Epoch 25/100: 100%|██████████| 27/27 [00:05<00:00,  5.08it/s, loss=0.492]

======================
Epoch 25
======================
VAL SUBSET ACC : 0.3889
VAL MICRO P/R/F1: 0.6434 / 0.7085 / 0.6744
VAL MACRO P/R/F1: 0.4368 / 0.4361 / 0.4264
VAL MIN LABEL F1: 0.2105
VAL WEIGHTED F1: 0.6623
VAL HAMMING LOSS: 0.1565

Epoch 26/100: 100%|██████████| 27/27 [00:05<00:00,  5.10it/s, loss=0.39]

======================
Epoch 26
======================
VAL SUBSET ACC : 0.4000
VAL MICRO P/R/F1: 0.6667 / 0.6883 / 0.6773
VAL MACRO P/R/F1: 0.4883 / 0.4040 / 0.4075
VAL MIN LABEL F1: 0.2069
VAL WEIGHTED F1: 0.6529
VAL HAMMING LOSS: 0.1500

Epoch 27/100: 100%|██████████| 27/27 [00:05<00:00,  5.06it/s, loss=0.322]

======================
Epoch 27
======================
VAL SUBSET ACC : 0.3667
VAL MICRO P/R/F1: 0.6118 / 0.7368 / 0.6685
VAL MACRO P/R/F1: 0.4344 / 0.4699 / 0.4360
VAL MIN LABEL F1: 0.2286
VAL WEIGHTED F1: 0.6688
VAL HAMMING LOSS: 0.1671

Epoch 28/100: 100%|██████████| 27/27 [00:05<00:00,  5.11it/s, loss=0.383]

======================
Epoch 28
======================
VAL SUBSET ACC : 0.3806
VAL MICRO P/R/F1: 0.6427 / 0.7065 / 0.6731
VAL MACRO P/R/F1: 0.4301 / 0.4288 / 0.4200
VAL MIN LABEL F1: 0.1765
VAL WEIGHTED F1: 0.6626
VAL HAMMING LOSS: 0.1569

Epoch 29/100: 100%|██████████| 27/27 [00:05<00:00,  5.09it/s, loss=0.401]

======================
Epoch 29
======================
VAL SUBSET ACC : 0.3222
VAL MICRO P/R/F1: 0.5877 / 0.7328 / 0.6523
VAL MACRO P/R/F1: 0.3928 / 0.4991 / 0.4338
VAL MIN LABEL F1: 0.2222
VAL WEIGHTED F1: 0.6680
VAL HAMMING LOSS: 0.1787

Epoch 30/100: 100%|██████████| 27/27 [00:05<00:00,  5.13it/s, loss=0.406]

======================
Epoch 30
======================
VAL SUBSET ACC : 0.3917
VAL MICRO P/R/F1: 0.6211 / 0.7166 / 0.6654
VAL MACRO P/R/F1: 0.4262 / 0.4323 / 0.4073
VAL MIN LABEL F1: 0.2222
VAL WEIGHTED F1: 0.6547
VAL HAMMING LOSS: 0.1648

Epoch 31/100: 100%|██████████| 27/27 [00:05<00:00,  5.09it/s, loss=0.306]

======================
Epoch 31
======================
VAL SUBSET ACC : 0.3667
VAL MICRO P/R/F1: 0.6288 / 0.7166 / 0.6698
VAL MACRO P/R/F1: 0.4281 / 0.4690 / 0.4370
VAL MIN LABEL F1: 0.2500
VAL WEIGHTED F1: 0.6717
VAL HAMMING LOSS: 0.1616

Epoch 32/100: 100%|██████████| 27/27 [00:05<00:00,  5.08it/s, loss=0.398]

======================
Epoch 32
======================
VAL SUBSET ACC : 0.3667
VAL MICRO P/R/F1: 0.6270 / 0.7247 / 0.6723
VAL MACRO P/R/F1: 0.4269 / 0.4676 / 0.4393
VAL MIN LABEL F1: 0.2128
VAL WEIGHTED F1: 0.6742
VAL HAMMING LOSS: 0.1616

Epoch 33/100: 100%|██████████| 27/27 [00:05<00:00,  5.09it/s, loss=0.338]

======================
Epoch 33
======================
VAL SUBSET ACC : 0.3417
VAL MICRO P/R/F1: 0.6149 / 0.7368 / 0.6703
VAL MACRO P/R/F1: 0.4308 / 0.5022 / 0.4531
VAL MIN LABEL F1: 0.2564
VAL WEIGHTED F1: 0.6790
VAL HAMMING LOSS: 0.1657

Epoch 34/100: 100%|██████████| 27/27 [00:05<00:00,  5.13it/s, loss=0.323]

======================
Epoch 34
======================
VAL SUBSET ACC : 0.3417
VAL MICRO P/R/F1: 0.6053 / 0.7449 / 0.6679
VAL MACRO P/R/F1: 0.4285 / 0.5030 / 0.4488
VAL MIN LABEL F1: 0.2222
VAL WEIGHTED F1: 0.6768
VAL HAMMING LOSS: 0.1694

Epoch 35/100: 100%|██████████| 27/27 [00:05<00:00,  5.12it/s, loss=0.394]

======================
Epoch 35
======================
VAL SUBSET ACC : 0.3583
VAL MICRO P/R/F1: 0.6403 / 0.7206 / 0.6781
VAL MACRO P/R/F1: 0.4248 / 0.4505 / 0.4296
VAL MIN LABEL F1: 0.2222
VAL WEIGHTED F1: 0.6659
VAL HAMMING LOSS: 0.1565

Epoch 36/100: 100%|██████████| 27/27 [00:05<00:00,  5.11it/s, loss=0.47]

======================
Epoch 36
======================
VAL SUBSET ACC : 0.3611
VAL MICRO P/R/F1: 0.6259 / 0.7348 / 0.6760
VAL MACRO P/R/F1: 0.4376 / 0.4866 / 0.4516
VAL MIN LABEL F1: 0.2632
VAL WEIGHTED F1: 0.6776
VAL HAMMING LOSS: 0.1611

Epoch 37/100: 100%|██████████| 27/27 [00:05<00:00,  5.07it/s, loss=0.294]

======================
Epoch 37
======================
VAL SUBSET ACC : 0.4111
VAL MICRO P/R/F1: 0.6777 / 0.7065 / 0.6918
VAL MACRO P/R/F1: 0.4571 / 0.4230 / 0.4326
VAL MIN LABEL F1: 0.2472
VAL WEIGHTED F1: 0.6691
VAL HAMMING LOSS: 0.1440

Epoch 38/100: 100%|██████████| 27/27 [00:05<00:00,  5.08it/s, loss=0.283]

======================
Epoch 38
======================
VAL SUBSET ACC : 0.3472
VAL MICRO P/R/F1: 0.6119 / 0.7308 / 0.6661
VAL MACRO P/R/F1: 0.4324 / 0.4796 / 0.4436
VAL MIN LABEL F1: 0.2500
VAL WEIGHTED F1: 0.6730
VAL HAMMING LOSS: 0.1676

Epoch 39/100: 100%|██████████| 27/27 [00:05<00:00,  5.15it/s, loss=0.3]

======================
Epoch 39
======================
VAL SUBSET ACC : 0.3944
VAL MICRO P/R/F1: 0.6388 / 0.7267 / 0.6799
VAL MACRO P/R/F1: 0.4491 / 0.4557 / 0.4401
VAL MIN LABEL F1: 0.2564
VAL WEIGHTED F1: 0.6713
VAL HAMMING LOSS: 0.1565

Epoch 40/100: 100%|██████████| 27/27 [00:05<00:00,  5.09it/s, loss=0.546]

======================
Epoch 40
======================
VAL SUBSET ACC : 0.3556
VAL MICRO P/R/F1: 0.6265 / 0.7368 / 0.6772
VAL MACRO P/R/F1: 0.4343 / 0.4817 / 0.4474
VAL MIN LABEL F1: 0.2632
VAL WEIGHTED F1: 0.6745
VAL HAMMING LOSS: 0.1606

Epoch 41/100: 100%|██████████| 27/27 [00:05<00:00,  5.14it/s, loss=0.25]

======================
Epoch 41
======================
VAL SUBSET ACC : 0.3694
VAL MICRO P/R/F1: 0.6329 / 0.7328 / 0.6792
VAL MACRO P/R/F1: 0.4440 / 0.4757 / 0.4487
VAL MIN LABEL F1: 0.2632
VAL WEIGHTED F1: 0.6758
VAL HAMMING LOSS: 0.1583

Epoch 42/100: 100%|██████████| 27/27 [00:05<00:00,  5.12it/s, loss=0.366]

======================
Epoch 42
======================
VAL SUBSET ACC : 0.3278
VAL MICRO P/R/F1: 0.6077 / 0.7308 / 0.6636
VAL MACRO P/R/F1: 0.4381 / 0.4949 / 0.4502
VAL MIN LABEL F1: 0.2778
VAL WEIGHTED F1: 0.6758
VAL HAMMING LOSS: 0.1694

Epoch 43/100: 100%|██████████| 27/27 [00:05<00:00,  5.10it/s, loss=0.337]

======================
Epoch 43
======================
VAL SUBSET ACC : 0.3444
VAL MICRO P/R/F1: 0.6254 / 0.7166 / 0.6679
VAL MACRO P/R/F1: 0.4330 / 0.4658 / 0.4414
VAL MIN LABEL F1: 0.2564
VAL WEIGHTED F1: 0.6724
VAL HAMMING LOSS: 0.1630

Epoch 44/100: 100%|██████████| 27/27 [00:05<00:00,  5.12it/s, loss=0.398]

======================
Epoch 44
======================
VAL SUBSET ACC : 0.3861
VAL MICRO P/R/F1: 0.6432 / 0.7227 / 0.6806
VAL MACRO P/R/F1: 0.4472 / 0.4546 / 0.4422
VAL MIN LABEL F1: 0.2632
VAL WEIGHTED F1: 0.6728
VAL HAMMING LOSS: 0.1551

Epoch 45/100: 100%|██████████| 27/27 [00:05<00:00,  5.14it/s, loss=0.332]

======================
Epoch 45
======================
VAL SUBSET ACC : 0.3528
VAL MICRO P/R/F1: 0.6166 / 0.7389 / 0.6722
VAL MACRO P/R/F1: 0.4211 / 0.4830 / 0.4434
VAL MIN LABEL F1: 0.2326
VAL WEIGHTED F1: 0.6727
VAL HAMMING LOSS: 0.1648

Epoch 46/100: 100%|██████████| 27/27 [00:05<00:00,  5.11it/s, loss=0.337]

======================
Epoch 46
======================
VAL SUBSET ACC : 0.3528
VAL MICRO P/R/F1: 0.6207 / 0.7389 / 0.6747
VAL MACRO P/R/F1: 0.4255 / 0.4820 / 0.4454
VAL MIN LABEL F1: 0.2500
VAL WEIGHTED F1: 0.6744
VAL HAMMING LOSS: 0.1630

Epoch 47/100: 100%|██████████| 27/27 [00:05<00:00,  5.08it/s, loss=0.417]

======================
Epoch 47
======================
VAL SUBSET ACC : 0.3667
VAL MICRO P/R/F1: 0.6212 / 0.7368 / 0.6741
VAL MACRO P/R/F1: 0.4314 / 0.4721 / 0.4410
VAL MIN LABEL F1: 0.2326
VAL WEIGHTED F1: 0.6721
VAL HAMMING LOSS: 0.1630

Epoch 48/100: 100%|██████████| 27/27 [00:05<00:00,  5.12it/s, loss=0.343]

======================
Epoch 48
======================
VAL SUBSET ACC : 0.3889
VAL MICRO P/R/F1: 0.6423 / 0.7308 / 0.6837
VAL MACRO P/R/F1: 0.4537 / 0.4582 / 0.4426
VAL MIN LABEL F1: 0.2222
VAL WEIGHTED F1: 0.6747
VAL HAMMING LOSS: 0.1546

Epoch 49/100: 100%|██████████| 27/27 [00:05<00:00,  5.14it/s, loss=0.381]

======================
Epoch 49
======================
VAL SUBSET ACC : 0.3694
VAL MICRO P/R/F1: 0.6289 / 0.7308 / 0.6760
VAL MACRO P/R/F1: 0.4299 / 0.4735 / 0.4455
VAL MIN LABEL F1: 0.2381
VAL WEIGHTED F1: 0.6742
VAL HAMMING LOSS: 0.1602

Epoch 50/100: 100%|██████████| 27/27 [00:05<00:00,  5.14it/s, loss=0.37]

======================
Epoch 50
======================
VAL SUBSET ACC : 0.3556
VAL MICRO P/R/F1: 0.6360 / 0.7146 / 0.6730
VAL MACRO P/R/F1: 0.4189 / 0.4435 / 0.4276
VAL MIN LABEL F1: 0.2069
VAL WEIGHTED F1: 0.6648
VAL HAMMING LOSS: 0.1588

Epoch 51/100: 100%|██████████| 27/27 [00:05<00:00,  5.09it/s, loss=0.346]

======================
Epoch 51
======================
VAL SUBSET ACC : 0.3722
VAL MICRO P/R/F1: 0.6388 / 0.7267 / 0.6799
VAL MACRO P/R/F1: 0.4225 / 0.4576 / 0.4382
VAL MIN LABEL F1: 0.2449
VAL WEIGHTED F1: 0.6701
VAL HAMMING LOSS: 0.1565

Epoch 52/100: 100%|██████████| 27/27 [00:05<00:00,  5.12it/s, loss=0.414]

======================
Epoch 52
======================
VAL SUBSET ACC : 0.3583
VAL MICRO P/R/F1: 0.6131 / 0.7409 / 0.6709
VAL MACRO P/R/F1: 0.4304 / 0.4739 / 0.4411
VAL MIN LABEL F1: 0.2449
VAL WEIGHTED F1: 0.6698
VAL HAMMING LOSS: 0.1662

Epoch 53/100: 100%|██████████| 27/27 [00:05<00:00,  5.11it/s, loss=0.316]

======================
Epoch 53
======================
VAL SUBSET ACC : 0.3667
VAL MICRO P/R/F1: 0.6335 / 0.7206 / 0.6742
VAL MACRO P/R/F1: 0.4456 / 0.4505 / 0.4350
VAL MIN LABEL F1: 0.2222
VAL WEIGHTED F1: 0.6691
VAL HAMMING LOSS: 0.1593

Epoch 54/100: 100%|██████████| 27/27 [00:05<00:00,  5.12it/s, loss=0.327]

======================
Epoch 54
======================
VAL SUBSET ACC : 0.3472
VAL MICRO P/R/F1: 0.6188 / 0.7328 / 0.6710
VAL MACRO P/R/F1: 0.4249 / 0.4766 / 0.4440
VAL MIN LABEL F1: 0.2727
VAL WEIGHTED F1: 0.6718
VAL HAMMING LOSS: 0.1644

Epoch 55/100: 100%|██████████| 27/27 [00:05<00:00,  5.07it/s, loss=0.347]

======================
Epoch 55
======================
VAL SUBSET ACC : 0.3889
VAL MICRO P/R/F1: 0.6461 / 0.7206 / 0.6813
VAL MACRO P/R/F1: 0.4380 / 0.4648 / 0.4490
VAL MIN LABEL F1: 0.2400
VAL WEIGHTED F1: 0.6734
VAL HAMMING LOSS: 0.1542

Epoch 56/100: 100%|██████████| 27/27 [00:05<00:00,  5.13it/s, loss=0.443]

======================
Epoch 56
======================
VAL SUBSET ACC : 0.3583
VAL MICRO P/R/F1: 0.6268 / 0.7206 / 0.6704
VAL MACRO P/R/F1: 0.4176 / 0.4587 / 0.4343
VAL MIN LABEL F1: 0.2353
VAL WEIGHTED F1: 0.6667
VAL HAMMING LOSS: 0.1620

Epoch 57/100: 100%|██████████| 27/27 [00:05<00:00,  5.11it/s, loss=0.293]

======================
Epoch 57
======================
VAL SUBSET ACC : 0.3694
VAL MICRO P/R/F1: 0.6239 / 0.7287 / 0.6723
VAL MACRO P/R/F1: 0.4207 / 0.4749 / 0.4420
VAL MIN LABEL F1: 0.2500
VAL WEIGHTED F1: 0.6709
VAL HAMMING LOSS: 0.1625

Epoch 58/100: 100%|██████████| 27/27 [00:05<00:00,  5.15it/s, loss=0.348]

======================
Epoch 58
======================
VAL SUBSET ACC : 0.3833
VAL MICRO P/R/F1: 0.6418 / 0.7146 / 0.6762
VAL MACRO P/R/F1: 0.4344 / 0.4526 / 0.4383
VAL MIN LABEL F1: 0.2273
VAL WEIGHTED F1: 0.6693
VAL HAMMING LOSS: 0.1565

Epoch 59/100: 100%|██████████| 27/27 [00:05<00:00,  5.10it/s, loss=0.294]

======================
Epoch 59
======================
VAL SUBSET ACC : 0.3972
VAL MICRO P/R/F1: 0.6499 / 0.7065 / 0.6770
VAL MACRO P/R/F1: 0.4804 / 0.4260 / 0.4229
VAL MIN LABEL F1: 0.2069
VAL WEIGHTED F1: 0.6620
VAL HAMMING LOSS: 0.1542

Epoch 60/100: 100%|██████████| 27/27 [00:05<00:00,  5.09it/s, loss=0.372]

======================
Epoch 60
======================
VAL SUBSET ACC : 0.3667
VAL MICRO P/R/F1: 0.6239 / 0.7186 / 0.6679
VAL MACRO P/R/F1: 0.4174 / 0.4534 / 0.4298
VAL MIN LABEL F1: 0.2143
VAL WEIGHTED F1: 0.6659
VAL HAMMING LOSS: 0.1634

Epoch 61/100: 100%|██████████| 27/27 [00:05<00:00,  5.11it/s, loss=0.476]

======================
Epoch 61
======================
VAL SUBSET ACC : 0.3861
VAL MICRO P/R/F1: 0.6357 / 0.7206 / 0.6755
VAL MACRO P/R/F1: 0.4324 / 0.4534 / 0.4363
VAL MIN LABEL F1: 0.2381
VAL WEIGHTED F1: 0.6689
VAL HAMMING LOSS: 0.1583

Epoch 62/100: 100%|██████████| 27/27 [00:05<00:00,  5.13it/s, loss=0.33]

======================
Epoch 62
======================
VAL SUBSET ACC : 0.3778
VAL MICRO P/R/F1: 0.6272 / 0.7287 / 0.6742
VAL MACRO P/R/F1: 0.4337 / 0.4691 / 0.4430
VAL MIN LABEL F1: 0.2326
VAL WEIGHTED F1: 0.6736
VAL HAMMING LOSS: 0.1611

Epoch 63/100: 100%|██████████| 27/27 [00:05<00:00,  5.12it/s, loss=0.373]

======================
Epoch 63
======================
VAL SUBSET ACC : 0.3917
VAL MICRO P/R/F1: 0.6395 / 0.7146 / 0.6750
VAL MACRO P/R/F1: 0.4312 / 0.4448 / 0.4304
VAL MIN LABEL F1: 0.2273
VAL WEIGHTED F1: 0.6665
VAL HAMMING LOSS: 0.1574

Epoch 64/100: 100%|██████████| 27/27 [00:05<00:00,  5.07it/s, loss=0.383]

======================
Epoch 64
======================
VAL SUBSET ACC : 0.3778
VAL MICRO P/R/F1: 0.6365 / 0.7267 / 0.6786
VAL MACRO P/R/F1: 0.4360 / 0.4657 / 0.4444
VAL MIN LABEL F1: 0.2326
VAL WEIGHTED F1: 0.6744
VAL HAMMING LOSS: 0.1574

Epoch 65/100: 100%|██████████| 27/27 [00:05<00:00,  5.10it/s, loss=0.397]

======================
Epoch 65
======================
VAL SUBSET ACC : 0.3889
VAL MICRO P/R/F1: 0.6436 / 0.7166 / 0.6782
VAL MACRO P/R/F1: 0.4381 / 0.4570 / 0.4409
VAL MIN LABEL F1: 0.2273
VAL WEIGHTED F1: 0.6728
VAL HAMMING LOSS: 0.1556

Epoch 66/100: 100%|██████████| 27/27 [00:05<00:00,  5.11it/s, loss=0.321]

======================
Epoch 66
======================
VAL SUBSET ACC : 0.3806
VAL MICRO P/R/F1: 0.6383 / 0.7287 / 0.6805
VAL MACRO P/R/F1: 0.4331 / 0.4634 / 0.4426
VAL MIN LABEL F1: 0.2273
VAL WEIGHTED F1: 0.6746
VAL HAMMING LOSS: 0.1565

Epoch 67/100: 100%|██████████| 27/27 [00:05<00:00,  5.14it/s, loss=0.305]

======================
Epoch 67
======================
VAL SUBSET ACC : 0.3556
VAL MICRO P/R/F1: 0.6164 / 0.7287 / 0.6679
VAL MACRO P/R/F1: 0.4156 / 0.4781 / 0.4391
VAL MIN LABEL F1: 0.2273
VAL WEIGHTED F1: 0.6725
VAL HAMMING LOSS: 0.1657

Epoch 68/100: 100%|██████████| 27/27 [00:05<00:00,  5.09it/s, loss=0.315]

======================
Epoch 68
======================
VAL SUBSET ACC : 0.3556
VAL MICRO P/R/F1: 0.6241 / 0.7126 / 0.6654
VAL MACRO P/R/F1: 0.4089 / 0.4500 / 0.4255
VAL MIN LABEL F1: 0.1923
VAL WEIGHTED F1: 0.6653
VAL HAMMING LOSS: 0.1639

Epoch 69/100: 100%|██████████| 27/27 [00:05<00:00,  5.12it/s, loss=0.316]

======================
Epoch 69
======================
VAL SUBSET ACC : 0.3278
VAL MICRO P/R/F1: 0.5987 / 0.7429 / 0.6631
VAL MACRO P/R/F1: 0.4021 / 0.4869 / 0.4360
VAL MIN LABEL F1: 0.2381
VAL WEIGHTED F1: 0.6687
VAL HAMMING LOSS: 0.1727

Epoch 70/100: 100%|██████████| 27/27 [00:05<00:00,  5.11it/s, loss=0.289]

======================
Epoch 70
======================
VAL SUBSET ACC : 0.3167
VAL MICRO P/R/F1: 0.5911 / 0.7490 / 0.6607
VAL MACRO P/R/F1: 0.4026 / 0.4913 / 0.4349
VAL MIN LABEL F1: 0.2381
VAL WEIGHTED F1: 0.6694
VAL HAMMING LOSS: 0.1759

Epoch 71/100: 100%|██████████| 27/27 [00:05<00:00,  5.10it/s, loss=0.344]

======================
Epoch 71
======================
VAL SUBSET ACC : 0.3444
VAL MICRO P/R/F1: 0.6119 / 0.7308 / 0.6661
VAL MACRO P/R/F1: 0.4127 / 0.4695 / 0.4292
VAL MIN LABEL F1: 0.2222
VAL WEIGHTED F1: 0.6670
VAL HAMMING LOSS: 0.1676

Epoch 72/100: 100%|██████████| 27/27 [00:05<00:00,  5.12it/s, loss=0.316]

======================
Epoch 72
======================
VAL SUBSET ACC : 0.3806
VAL MICRO P/R/F1: 0.6484 / 0.7166 / 0.6808
VAL MACRO P/R/F1: 0.4405 / 0.4538 / 0.4382
VAL MIN LABEL F1: 0.2286
VAL WEIGHTED F1: 0.6719
VAL HAMMING LOSS: 0.1537

Epoch 73/100: 100%|██████████| 27/27 [00:05<00:00,  5.11it/s, loss=0.381]

======================
Epoch 73
======================
VAL SUBSET ACC : 0.3806
VAL MICRO P/R/F1: 0.6425 / 0.7166 / 0.6775
VAL MACRO P/R/F1: 0.4361 / 0.4519 / 0.4342
VAL MIN LABEL F1: 0.2286
VAL WEIGHTED F1: 0.6694
VAL HAMMING LOSS: 0.1560

Epoch 74/100: 100%|██████████| 27/27 [00:05<00:00,  5.12it/s, loss=0.412]

======================
Epoch 74
======================
VAL SUBSET ACC : 0.3778
VAL MICRO P/R/F1: 0.6484 / 0.7166 / 0.6808
VAL MACRO P/R/F1: 0.4359 / 0.4489 / 0.4349
VAL MIN LABEL F1: 0.2286
VAL WEIGHTED F1: 0.6702
VAL HAMMING LOSS: 0.1537

Epoch 75/100: 100%|██████████| 27/27 [00:05<00:00,  5.11it/s, loss=0.298]

======================
Epoch 75
======================
VAL SUBSET ACC : 0.3806
VAL MICRO P/R/F1: 0.6507 / 0.7166 / 0.6821
VAL MACRO P/R/F1: 0.4405 / 0.4470 / 0.4354
VAL MIN LABEL F1: 0.2286
VAL WEIGHTED F1: 0.6702
VAL HAMMING LOSS: 0.1528

Epoch 76/100: 100%|██████████| 27/27 [00:05<00:00,  5.12it/s, loss=0.274]

======================
Epoch 76
======================
VAL SUBSET ACC : 0.3472
VAL MICRO P/R/F1: 0.6139 / 0.7308 / 0.6673
VAL MACRO P/R/F1: 0.4215 / 0.4703 / 0.4316
VAL MIN LABEL F1: 0.2286
VAL WEIGHTED F1: 0.6690
VAL HAMMING LOSS: 0.1667

Epoch 77/100: 100%|██████████| 27/27 [00:05<00:00,  5.05it/s, loss=0.348]

======================
Epoch 77
======================
VAL SUBSET ACC : 0.3417
VAL MICRO P/R/F1: 0.6102 / 0.7287 / 0.6642
VAL MACRO P/R/F1: 0.4190 / 0.4697 / 0.4300
VAL MIN LABEL F1: 0.2222
VAL WEIGHTED F1: 0.6675
VAL HAMMING LOSS: 0.1685

Epoch 78/100: 100%|██████████| 27/27 [00:05<00:00,  5.10it/s, loss=0.284]

======================
Epoch 78
======================
VAL SUBSET ACC : 0.3472
VAL MICRO P/R/F1: 0.6200 / 0.7267 / 0.6692
VAL MACRO P/R/F1: 0.4072 / 0.4707 / 0.4347
VAL MIN LABEL F1: 0.2273
VAL WEIGHTED F1: 0.6699
VAL HAMMING LOSS: 0.1644

Epoch 79/100: 100%|██████████| 27/27 [00:05<00:00,  5.14it/s, loss=0.307]

======================
Epoch 79
======================
VAL SUBSET ACC : 0.3639
VAL MICRO P/R/F1: 0.6301 / 0.7206 / 0.6723
VAL MACRO P/R/F1: 0.4067 / 0.4584 / 0.4303
VAL MIN LABEL F1: 0.2222
VAL WEIGHTED F1: 0.6685
VAL HAMMING LOSS: 0.1606

Epoch 80/100: 100%|██████████| 27/27 [00:05<00:00,  5.12it/s, loss=0.337]

======================
Epoch 80
======================
VAL SUBSET ACC : 0.3722
VAL MICRO P/R/F1: 0.6352 / 0.7227 / 0.6761
VAL MACRO P/R/F1: 0.4149 / 0.4590 / 0.4348
VAL MIN LABEL F1: 0.2273
VAL WEIGHTED F1: 0.6697
VAL HAMMING LOSS: 0.1583

Epoch 81/100: 100%|██████████| 27/27 [00:05<00:00,  5.08it/s, loss=0.377]

======================
Epoch 81
======================
VAL SUBSET ACC : 0.3556
VAL MICRO P/R/F1: 0.6265 / 0.7267 / 0.6729
VAL MACRO P/R/F1: 0.4058 / 0.4630 / 0.4315
VAL MIN LABEL F1: 0.2222
VAL WEIGHTED F1: 0.6693
VAL HAMMING LOSS: 0.1616

Epoch 82/100: 100%|██████████| 27/27 [00:05<00:00,  5.08it/s, loss=0.359]

======================
Epoch 82
======================
VAL SUBSET ACC : 0.3583
VAL MICRO P/R/F1: 0.6307 / 0.7227 / 0.6736
VAL MACRO P/R/F1: 0.4138 / 0.4619 / 0.4350
VAL MIN LABEL F1: 0.2326
VAL WEIGHTED F1: 0.6692
VAL HAMMING LOSS: 0.1602

Epoch 83/100: 100%|██████████| 27/27 [00:05<00:00,  5.13it/s, loss=0.262]

======================
Epoch 83
======================
VAL SUBSET ACC : 0.3861
VAL MICRO P/R/F1: 0.6500 / 0.7105 / 0.6789
VAL MACRO P/R/F1: 0.4239 / 0.4459 / 0.4326
VAL MIN LABEL F1: 0.2326
VAL WEIGHTED F1: 0.6688
VAL HAMMING LOSS: 0.1537

Epoch 84/100: 100%|██████████| 27/27 [00:05<00:00,  5.09it/s, loss=0.32]

======================
Epoch 84
======================
VAL SUBSET ACC : 0.3528
VAL MICRO P/R/F1: 0.6207 / 0.7287 / 0.6704
VAL MACRO P/R/F1: 0.4074 / 0.4703 / 0.4345
VAL MIN LABEL F1: 0.2326
VAL WEIGHTED F1: 0.6700
VAL HAMMING LOSS: 0.1639

Epoch 85/100: 100%|██████████| 27/27 [00:05<00:00,  5.13it/s, loss=0.388]

======================
Epoch 85
======================
VAL SUBSET ACC : 0.3500
VAL MICRO P/R/F1: 0.6228 / 0.7287 / 0.6716
VAL MACRO P/R/F1: 0.4104 / 0.4703 / 0.4361
VAL MIN LABEL F1: 0.2326
VAL WEIGHTED F1: 0.6708
VAL HAMMING LOSS: 0.1630

Epoch 86/100: 100%|██████████| 27/27 [00:05<00:00,  5.11it/s, loss=0.355]

======================
Epoch 86
======================
VAL SUBSET ACC : 0.3639
VAL MICRO P/R/F1: 0.6281 / 0.7247 / 0.6729
VAL MACRO P/R/F1: 0.4122 / 0.4634 / 0.4344
VAL MIN LABEL F1: 0.2326
VAL WEIGHTED F1: 0.6696
VAL HAMMING LOSS: 0.1611

Epoch 87/100: 100%|██████████| 27/27 [00:05<00:00,  5.13it/s, loss=0.278]

======================
Epoch 87
======================
VAL SUBSET ACC : 0.3667
VAL MICRO P/R/F1: 0.6357 / 0.7206 / 0.6755
VAL MACRO P/R/F1: 0.4162 / 0.4584 / 0.4349
VAL MIN LABEL F1: 0.2326
VAL WEIGHTED F1: 0.6698
VAL HAMMING LOSS: 0.1583

Epoch 88/100: 100%|██████████| 27/27 [00:05<00:00,  5.12it/s, loss=0.354]

======================
Epoch 88
======================
VAL SUBSET ACC : 0.3583
VAL MICRO P/R/F1: 0.6285 / 0.7227 / 0.6723
VAL MACRO P/R/F1: 0.4154 / 0.4647 / 0.4362
VAL MIN LABEL F1: 0.2381
VAL WEIGHTED F1: 0.6697
VAL HAMMING LOSS: 0.1611

Epoch 89/100: 100%|██████████| 27/27 [00:05<00:00,  5.09it/s, loss=0.327]

======================
Epoch 89
======================
VAL SUBSET ACC : 0.3750
VAL MICRO P/R/F1: 0.6311 / 0.7308 / 0.6773
VAL MACRO P/R/F1: 0.4187 / 0.4610 / 0.4358
VAL MIN LABEL F1: 0.2381
VAL WEIGHTED F1: 0.6708
VAL HAMMING LOSS: 0.1593

Epoch 90/100: 100%|██████████| 27/27 [00:05<00:00,  5.10it/s, loss=0.288]

======================
Epoch 90
======================
VAL SUBSET ACC : 0.3722
VAL MICRO P/R/F1: 0.6346 / 0.7206 / 0.6749
VAL MACRO P/R/F1: 0.4192 / 0.4641 / 0.4386
VAL MIN LABEL F1: 0.2381
VAL WEIGHTED F1: 0.6712
VAL HAMMING LOSS: 0.1588

Epoch 91/100: 100%|██████████| 27/27 [00:05<00:00,  5.11it/s, loss=0.254]

======================
Epoch 91
======================
VAL SUBSET ACC : 0.3722
VAL MICRO P/R/F1: 0.6333 / 0.7308 / 0.6786
VAL MACRO P/R/F1: 0.4184 / 0.4652 / 0.4385
VAL MIN LABEL F1: 0.2381
VAL WEIGHTED F1: 0.6712
VAL HAMMING LOSS: 0.1583

Epoch 92/100: 100%|██████████| 27/27 [00:05<00:00,  5.07it/s, loss=0.315]

======================
Epoch 92
======================
VAL SUBSET ACC : 0.3667
VAL MICRO P/R/F1: 0.6307 / 0.7227 / 0.6736
VAL MACRO P/R/F1: 0.4155 / 0.4628 / 0.4358
VAL MIN LABEL F1: 0.2381
VAL WEIGHTED F1: 0.6695
VAL HAMMING LOSS: 0.1602

Epoch 93/100: 100%|██████████| 27/27 [00:05<00:00,  5.11it/s, loss=0.281]

======================
Epoch 93
======================
VAL SUBSET ACC : 0.3389
VAL MICRO P/R/F1: 0.6007 / 0.7368 / 0.6618
VAL MACRO P/R/F1: 0.4081 / 0.4900 / 0.4383
VAL MIN LABEL F1: 0.2381
VAL WEIGHTED F1: 0.6717
VAL HAMMING LOSS: 0.1722

Epoch 94/100: 100%|██████████| 27/27 [00:05<00:00,  5.11it/s, loss=0.259]

======================
Epoch 94
======================
VAL SUBSET ACC : 0.3500
VAL MICRO P/R/F1: 0.6086 / 0.7429 / 0.6691
VAL MACRO P/R/F1: 0.4089 / 0.4860 / 0.4393
VAL MIN LABEL F1: 0.2381
VAL WEIGHTED F1: 0.6723
VAL HAMMING LOSS: 0.1681

Epoch 95/100: 100%|██████████| 27/27 [00:05<00:00,  5.08it/s, loss=0.272]

======================
Epoch 95
======================
VAL SUBSET ACC : 0.3417
VAL MICRO P/R/F1: 0.6033 / 0.7449 / 0.6667
VAL MACRO P/R/F1: 0.4052 / 0.4885 / 0.4380
VAL MIN LABEL F1: 0.2381
VAL WEIGHTED F1: 0.6717
VAL HAMMING LOSS: 0.1704

Epoch 96/100: 100%|██████████| 27/27 [00:05<00:00,  5.09it/s, loss=0.32]

======================
Epoch 96
======================
VAL SUBSET ACC : 0.3472
VAL MICRO P/R/F1: 0.6046 / 0.7429 / 0.6667
VAL MACRO P/R/F1: 0.4061 / 0.4860 / 0.4373
VAL MIN LABEL F1: 0.2381
VAL WEIGHTED F1: 0.6712
VAL HAMMING LOSS: 0.1699

Epoch 97/100: 100%|██████████| 27/27 [00:05<00:00,  5.08it/s, loss=0.201]

======================
Epoch 97
======================
VAL SUBSET ACC : 0.3306
VAL MICRO P/R/F1: 0.5954 / 0.7389 / 0.6594
VAL MACRO P/R/F1: 0.4045 / 0.4925 / 0.4371
VAL MIN LABEL F1: 0.2381
VAL WEIGHTED F1: 0.6712
VAL HAMMING LOSS: 0.1745

Epoch 98/100: 100%|██████████| 27/27 [00:05<00:00,  5.12it/s, loss=0.283]

======================
Epoch 98
======================
VAL SUBSET ACC : 0.3694
VAL MICRO P/R/F1: 0.6341 / 0.7227 / 0.6755
VAL MACRO P/R/F1: 0.4184 / 0.4647 / 0.4384
VAL MIN LABEL F1: 0.2381
VAL WEIGHTED F1: 0.6719
VAL HAMMING LOSS: 0.1588

Epoch 99/100: 100%|██████████| 27/27 [00:05<00:00,  5.09it/s, loss=0.315]

======================
Epoch 99
======================
VAL SUBSET ACC : 0.3333
VAL MICRO P/R/F1: 0.5984 / 0.7389 / 0.6612
VAL MACRO P/R/F1: 0.4066 / 0.4925 / 0.4386
VAL MIN LABEL F1: 0.2381
VAL WEIGHTED F1: 0.6720
VAL HAMMING LOSS: 0.1731

Epoch 100/100: 100%|██████████| 27/27 [00:05<00:00,  5.12it/s, loss=0.329]

======================
Epoch 100
======================
VAL SUBSET ACC : 0.3333
VAL MICRO P/R/F1: 0.5984 / 0.7389 / 0.6612
VAL MACRO P/R/F1: 0.4066 / 0.4925 / 0.4386
VAL MIN LABEL F1: 0.2381
VAL WEIGHTED F1: 0.6720
VAL HAMMING LOSS: 0.1731

In [22]:
val_result = evaluate(
    final_model,
    val_loader
)

best_thresholds = optimize_thresholds(
    val_result["labels"],
    val_result["probs"]
)

val_result_tuned = evaluate(
    final_model,
    val_loader,
    best_thresholds
)

print("\n======================")
print("BEST THRESHOLDS FROM FINAL VALIDATION")
print("======================")

for label, thr in zip(
    LABEL_COLUMNS,
    best_thresholds
):
    print(f"{label}: {thr:.3f}")

print("\nVALIDATION RESULT AFTER THRESHOLD TUNING")
print("macro_f1:", val_result_tuned["macro_f1"])
print("micro_f1:", val_result_tuned["micro_f1"])
print("min_per_label_f1:", val_result_tuned["min_per_label_f1"])
print("subset_accuracy:", val_result_tuned["subset_accuracy"])

======================
BEST THRESHOLDS FROM FINAL VALIDATION
======================
Happiness: 0.265
Sadness: 0.430
Anger: 0.230
Disgust: 0.295
Surprise: 0.410
Fear: 0.215

VALIDATION RESULT AFTER THRESHOLD TUNING
macro_f1: 0.4385805866069024
micro_f1: 0.6612318840579711
min_per_label_f1: 0.23809523809523808
subset_accuracy: 0.3333333333333333

In [23]:
def summarize_result(name, result):

    return {
        "split": name,
        "subset_accuracy_exact_match": result["subset_accuracy"],
        "micro_precision": result["micro_precision"],
        "micro_recall": result["micro_recall"],
        "micro_f1": result["micro_f1"],
        "macro_precision": result["macro_precision"],
        "macro_recall": result["macro_recall"],
        "macro_f1": result["macro_f1"],
        "weighted_f1": result["weighted_f1"],
        "min_per_label_f1": result["min_per_label_f1"],
        "hamming_loss": result["hamming_loss"]
    }


train_result = evaluate(
    final_model,
    train_eval_loader,
    best_thresholds
)

val_result_final = evaluate(
    final_model,
    val_loader,
    best_thresholds
)

test_result = evaluate(
    final_model,
    test_loader,
    best_thresholds
)

metrics_summary = pd.DataFrame([
    summarize_result("train", train_result),
    summarize_result("validation", val_result_final),
    summarize_result("test", test_result)
])

print("\n======================")
print("FINAL METRICS SUMMARY")
print("======================")
display(metrics_summary)

print("\n======================")
print("BEST THRESHOLDS")
print("======================")

threshold_df = pd.DataFrame({
    "label": LABEL_COLUMNS,
    "threshold": best_thresholds
})

display(threshold_df)

print("\n======================")
print("TEST SET MAIN RESULT")
print("======================")

print(f"Subset Accuracy / Exact Match : {test_result['subset_accuracy']:.4f}")
print(f"Micro Precision              : {test_result['micro_precision']:.4f}")
print(f"Micro Recall                 : {test_result['micro_recall']:.4f}")
print(f"Micro F1                     : {test_result['micro_f1']:.4f}")
print(f"Macro Precision              : {test_result['macro_precision']:.4f}")
print(f"Macro Recall                 : {test_result['macro_recall']:.4f}")
print(f"Macro F1                     : {test_result['macro_f1']:.4f}")
print(f"Weighted F1                  : {test_result['weighted_f1']:.4f}")
print(f"Min Per-label F1             : {test_result['min_per_label_f1']:.4f}")
print(f"Hamming Loss                 : {test_result['hamming_loss']:.4f}")

======================
FINAL METRICS SUMMARY
======================

,split,subset_accuracy_exact_match,micro_precision,micro_recall,micro_f1,macro_precision,macro_recall,macro_f1,weighted_f1,min_per_label_f1,hamming_loss
0,train,0.557738,0.729359,0.922044,0.814461,0.664365,0.845809,0.735417,0.824661,0.607717,0.096230
1,validation,0.333333,0.598361,0.738866,0.661232,0.406628,0.492513,0.438581,0.672040,0.238095,0.173148
2,test,0.327778,0.591803,0.724900,0.651625,0.385340,0.478694,0.422466,0.664349,0.080000,0.178704

======================
BEST THRESHOLDS
======================

       label  threshold
0  Happiness      0.265
1    Sadness      0.430
2      Anger      0.230
3    Disgust      0.295
4   Surprise      0.410
5       Fear      0.215

======================
TEST SET MAIN RESULT
======================
Subset Accuracy / Exact Match : 0.3278
Micro Precision              : 0.5918
Micro Recall                 : 0.7249
Micro F1                     : 0.6516
Macro Precision              : 0.3853
Macro Recall                 : 0.4787
Macro F1                     : 0.4225
Weighted F1                  : 0.6643
Min Per-label F1             : 0.0800
Hamming Loss                 : 0.1787

In [24]:
print("\n======================")
print("TEST CLASSIFICATION REPORT")
print("======================")

report_dict = classification_report(
    test_result["labels"],
    test_result["preds"],
    target_names=LABEL_COLUMNS,
    zero_division=0,
    output_dict=True
)

per_label_report = pd.DataFrame(report_dict).T
display(per_label_report)

per_label_metrics = pd.DataFrame({
    "label": LABEL_COLUMNS,
    "precision": test_result["per_label_precision"],
    "recall": test_result["per_label_recall"],
    "f1_score": test_result["per_label_f1"],
    "true_support": test_result["labels"].sum(axis=0).astype(int),
    "predicted_positive": test_result["preds"].sum(axis=0).astype(int),
    "threshold": best_thresholds
})

print("\n======================")
print("PER-LABEL TEST METRICS")
print("======================")
display(per_label_metrics)

print("\n======================")
print("TEST MULTI-LABEL CONFUSION MATRIX")
print("======================")

mcm = multilabel_confusion_matrix(
    test_result["labels"],
    test_result["preds"]
)

confusion_rows = []

for i, label in enumerate(LABEL_COLUMNS):
    tn, fp, fn, tp = mcm[i].ravel()

    confusion_rows.append({
        "label": label,
        "TP": int(tp),
        "FP": int(fp),
        "FN": int(fn),
        "TN": int(tn)
    })

confusion_df = pd.DataFrame(confusion_rows)
display(confusion_df)

test_probs_df = pd.DataFrame(
    test_result["probs"],
    columns=[f"prob_{label}" for label in LABEL_COLUMNS]
)

test_preds_df = pd.DataFrame(
    test_result["preds"],
    columns=[f"pred_{label}" for label in LABEL_COLUMNS]
)

test_true_df = test_df[[TEXT_COLUMN] + LABEL_COLUMNS].copy()

test_predictions_output = pd.concat(
    [
        test_true_df.reset_index(drop=True),
        test_probs_df.reset_index(drop=True),
        test_preds_df.reset_index(drop=True)
    ],
    axis=1
)

metrics_summary.to_csv(
    "/content/mbert_sied_original_metrics_summary.csv",
    index=False,
    encoding="utf-8-sig"
)

threshold_df.to_csv(
    "/content/mbert_sied_original_thresholds.csv",
    index=False,
    encoding="utf-8-sig"
)

per_label_report.to_csv(
    "/content/mbert_sied_original_per_label_report.csv",
    encoding="utf-8-sig"
)

per_label_metrics.to_csv(
    "/content/mbert_sied_original_per_label_metrics.csv",
    index=False,
    encoding="utf-8-sig"
)

confusion_df.to_csv(
    "/content/mbert_sied_original_confusion_matrix.csv",
    index=False,
    encoding="utf-8-sig"
)

test_predictions_output.to_csv(
    "/content/mbert_sied_original_test_predictions.csv",
    index=False,
    encoding="utf-8-sig"
)

print("\nEXPORTED FILES")
print("/content/mbert_sied_original_metrics_summary.csv")
print("/content/mbert_sied_original_thresholds.csv")
print("/content/mbert_sied_original_per_label_report.csv")
print("/content/mbert_sied_original_per_label_metrics.csv")
print("/content/mbert_sied_original_confusion_matrix.csv")
print("/content/mbert_sied_original_test_predictions.csv")

======================
TEST CLASSIFICATION REPORT
======================

              precision    recall  f1-score  support
Happiness      0.451613  0.538462  0.491228     26.0
Sadness        0.840000  0.961268  0.896552    284.0
Anger          0.225806  0.304348  0.259259     46.0
Disgust        0.480519  0.513889  0.496644     72.0
Surprise       0.083333  0.076923  0.080000     26.0
Fear           0.230769  0.477273  0.311111     44.0
micro avg      0.591803  0.724900  0.651625    498.0
macro avg      0.385340  0.478694  0.422466    498.0
weighted avg   0.617685  0.724900  0.664349    498.0
samples avg    0.631620  0.719907  0.639630    498.0

======================
PER-LABEL TEST METRICS
======================

,label,precision,recall,f1_score,true_support,predicted_positive,threshold
0,Happiness,0.451613,0.538462,0.491228,26,31,0.265
1,Sadness,0.840000,0.961268,0.896552,284,325,0.430
2,Anger,0.225806,0.304348,0.259259,46,62,0.230
3,Disgust,0.480519,0.513889,0.496644,72,77,0.295
4,Surprise,0.083333,0.076923,0.080000,26,24,0.410
5,Fear,0.230769,0.477273,0.311111,44,91,0.215

======================
TEST MULTI-LABEL CONFUSION MATRIX
======================

       label   TP  FP  FN   TN
0  Happiness   14  17  12  317
1    Sadness  273  52  11   24
2      Anger   14  48  32  266
3    Disgust   37  40  35  248
4   Surprise    2  22  24  312
5       Fear   21  70  23  246

EXPORTED FILES
/content/mbert_sied_original_metrics_summary.csv
/content/mbert_sied_original_thresholds.csv
/content/mbert_sied_original_per_label_report.csv
/content/mbert_sied_original_per_label_metrics.csv
/content/mbert_sied_original_confusion_matrix.csv
/content/mbert_sied_original_test_predictions.csv

In [25]:
SAVE_PATH = "/content/final_mbert_sied_original_xtransformers_strong_optimized.pt"

torch.save(
    {
        "model_state_dict": final_model.state_dict(),
        "thresholds": best_thresholds,
        "best_params": best_params,
        "labels": LABEL_COLUMNS,
        "model_name": MODEL_NAME,
        "max_len": MAX_LEN,
        "dataset": "SIED-Thai original/unbalanced (2,400 rows)",
        "seed": SEED,
        "epochs": EPOCHS,
        "batch_size": BATCH_SIZE,
        "optuna_trials": N_TRIALS,
        "optuna_epochs": OPTUNA_EPOCHS,
        "objective": "0.45 macro_f1 + 0.25 micro_f1 + 0.20 min_per_label_f1 + 0.10 subset_accuracy",
        "note": "Encoder comparison version; encoder frozen; same Strong Optimized EAQD/x-transformers framework."
    },
    SAVE_PATH
)

print("\nMODEL SAVED:", SAVE_PATH)

MODEL SAVED: /content/final_mbert_sied_original_xtransformers_strong_optimized.pt

In [26]:
import shutil
from IPython.display import FileLink, display

OUTPUT_PATH = "/kaggle/working/final_mbert_sied_original_xtransformers_strong_optimized.pt"

# คัดลอกโมเดลที่เซฟแล้ว ไม่ต้องเทรนใหม่
shutil.copy2(SAVE_PATH, OUTPUT_PATH)
display(FileLink(OUTPUT_PATH))

/kaggle/working/final_mbert_sied_original_xtransformers_strong_optimized.pt