In [1]:
import time
SESSION_STARTED = time.monotonic()
!pip install -q transformers sentencepiece x-transformers optuna==4.6.0 scikit-learn
!apt-get -qq update
!apt-get -qq install -y unrar

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 107.3/107.3 kB 2.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 404.7/404.7 kB 10.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.1/143.1 kB 8.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 163.8/163.8 kB 8.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.6/61.6 kB 3.4 MB/s eta 0:00:00
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)

# mBERT + x-transformers — Thai Depression — Strong Optimized

เวอร์ชันนี้เปลี่ยนเฉพาะ encoder เป็น `bert-base-multilingual-cased` และปรับ data loader ให้ตรงกับ **Thai Depression dataset ที่ผู้ใช้อัปโหลด**

- ใช้ split ที่ dataset ให้มาโดยตรง: `train.json`, `valid.json`, `test.json`
- ไม่ทำ split ใหม่
- Label: `depression`, `no_depression`
- คง `MAX_LEN=128`, `EPOCHS=100`, `BATCH_SIZE=64`
- คง Optuna Strong Optimized framework เดิม: `N_TRIALS=25`, `OPTUNA_EPOCHS=35`
- encoder frozen
- decoder, pooling, classifier, loss search, threshold tuning และ objective คงเดิม

In [2]:
import os
import json
import random
import warnings
import subprocess
import shutil
from pathlib import Path
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd

from tqdm import tqdm

import torch
import torch.nn as nn

from torch.utils.data import Dataset, DataLoader

from transformers import (
    AutoTokenizer,
    AutoModel,
    get_linear_schedule_with_warmup
)

from x_transformers import Decoder

from sklearn.model_selection import train_test_split

from sklearn.metrics import (
    f1_score,
    accuracy_score,
    precision_score,
    recall_score,
    classification_report,
    hamming_loss,
    multilabel_confusion_matrix
)

import optuna

In [3]:
SEED = 42

random.seed(SEED)
np.random.seed(SEED)

torch.manual_seed(SEED)
torch.cuda.manual_seed_all(SEED)

In [4]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print("DEVICE:", device)

DEVICE: cuda

In [5]:
MODEL_NAME = "bert-base-multilingual-cased"

MAX_LEN = 128
EPOCHS = 100
BATCH_SIZE = 64
NUM_LABELS = 2

N_TRIALS = 25
OPTUNA_EPOCHS = 35

LABEL_COLUMNS = [
    "depression",
    "no_depression"
]

TEXT_COLUMN = "text"

# First run: leave empty. Next run: attach your mBERT checkpoint as Input.
# Set an explicit path to override any older checkpoint in /kaggle/working.
RESUME_FROM = "/kaggle/input/datasets/kmkimmy/checkpoint-latest1/checkpoint_latest.pt"
# Example: RESUME_FROM = "/kaggle/input/my-mbert-backup/checkpoint_latest.pt"
SESSION_BUDGET_HOURS = 12.0

In [6]:
from pathlib import Path
import torch
import optuna

SOURCE = Path(
    "/kaggle/input/datasets/kmkimmy/checkpoint-latest1/checkpoint_latest.pt"
)
TARGET = Path("/kaggle/working/checkpoint_latest.pt")

checkpoint = torch.load(
    SOURCE,
    map_location="cpu",
    weights_only=False
)

current_config = dict(
    format=1,
    optuna_version=optuna.__version__,
    model_name=MODEL_NAME,
    max_len=MAX_LEN,
    batch_size=BATCH_SIZE,
    epochs=EPOCHS,
    optuna_epochs=OPTUNA_EPOCHS,
    n_trials=N_TRIALS,
    labels=LABEL_COLUMNS,
)

saved_config = checkpoint["config"]
legacy_config = dict(current_config, epochs=1)

if saved_config == legacy_config:
    checkpoint["config"] = current_config
    checkpoint["training"] = None
    print("Converted EPOCHS 1 -> 100; final training will restart")
elif saved_config == current_config:
    print("Checkpoint already uses EPOCHS =", EPOCHS)
else:
    raise ValueError(
        f"Checkpoint has other incompatible settings\n"
        f"checkpoint: {saved_config}\n"
        f"current: {current_config}"
    )

torch.save(checkpoint, TARGET)

RESUME_FROM = str(TARGET)
print("Checkpoint ready:", TARGET)

Converted EPOCHS 1 -> 100; final training will restart
Checkpoint ready: /kaggle/working/checkpoint_latest.pt

In [7]:
# Latest checkpoint helpers
import time
import os
import shutil

WORK_DIR = Path("/kaggle/working")
WORK_DIR.mkdir(parents=True, exist_ok=True)
CHECKPOINT_PATH = WORK_DIR / "checkpoint_latest.pt"

CHECKPOINT_CONFIG = dict(
    format=1, optuna_version=optuna.__version__, model_name=MODEL_NAME,
    max_len=MAX_LEN, batch_size=BATCH_SIZE, epochs=EPOCHS,
    optuna_epochs=OPTUNA_EPOCHS, n_trials=N_TRIALS, labels=LABEL_COLUMNS
)


class SessionTimeLimit(Exception):
    pass


def session_expired():
    return time.monotonic() - SESSION_STARTED >= SESSION_BUDGET_HOURS * 3600


def capture_rng():
    return dict(python=random.getstate(), numpy=np.random.get_state(),
                torch=torch.get_rng_state(),
                cuda=torch.cuda.get_rng_state_all() if torch.cuda.is_available() else [])


def restore_rng(state):
    random.setstate(state["python"])
    np.random.set_state(state["numpy"])
    torch.set_rng_state(state["torch"].cpu())
    if state["cuda"] and torch.cuda.is_available():
        torch.cuda.set_rng_state_all([s.cpu() for s in state["cuda"]])


# Explicit selection takes priority over any existing working checkpoint.
source_checkpoint = None
if RESUME_FROM:
    source_checkpoint = Path(RESUME_FROM)
    if not source_checkpoint.is_file():
        raise FileNotFoundError(f"Checkpoint not found: {source_checkpoint}")
elif CHECKPOINT_PATH.is_file():
    source_checkpoint = CHECKPOINT_PATH
else:
    candidates = sorted(Path("/kaggle/input").rglob("checkpoint_latest.pt"))
    if len(candidates) > 1:
        raise ValueError("Multiple checkpoints found; set RESUME_FROM to the intended mBERT file")
    if candidates:
        source_checkpoint = candidates[0]

# Load only your own checkpoint: it contains Python objects.
# Validate before replacing a working checkpoint, so a wrong file cannot erase it.
if source_checkpoint is not None:
    CHECKPOINT = torch.load(source_checkpoint, map_location="cpu", weights_only=False)
    if CHECKPOINT.get("config") != CHECKPOINT_CONFIG:
        raise ValueError(
            "Checkpoint configuration/version differs. Use an mBERT checkpoint from this notebook, "
            "with the same dataset, settings and Optuna version. "
            f"Saved configuration: {CHECKPOINT.get('config')}; current: {CHECKPOINT_CONFIG}"
        )
    if source_checkpoint.resolve() != CHECKPOINT_PATH.resolve():
        temporary_import = CHECKPOINT_PATH.with_suffix(".import.tmp")
        try:
            shutil.copy2(source_checkpoint, temporary_import)
            os.replace(temporary_import, CHECKPOINT_PATH)
        finally:
            temporary_import.unlink(missing_ok=True)
    study = CHECKPOINT["study"]
    restore_rng(CHECKPOINT["rng"])
    print("Loaded:", source_checkpoint)
    print("Working checkpoint:", CHECKPOINT_PATH)
    print("Completed trials:", len(study.get_trials(states=[optuna.trial.TrialState.COMPLETE])), "/", N_TRIALS)
    saved_stage = CHECKPOINT.get("training")
    if saved_stage:
        print("Saved stage:", saved_stage["tag"], "completed epochs:",
              saved_stage["completed_epochs"], "/", saved_stage["epochs"])
else:
    study = optuna.create_study(
        direction="maximize",
        sampler=optuna.samplers.TPESampler(seed=SEED, multivariate=True)
    )
    CHECKPOINT = dict(config=CHECKPOINT_CONFIG, study=study,
                      active_trial=None, training=None)
    print("New run: no checkpoint loaded")

SESSION_STOPPED = False
FINAL_TRAINING_COMPLETE = False


def save_latest():
    CHECKPOINT["rng"] = capture_rng()
    temporary = CHECKPOINT_PATH.with_suffix(".tmp")
    try:
        torch.save(CHECKPOINT, temporary)
        os.replace(temporary, CHECKPOINT_PATH)
    finally:
        temporary.unlink(missing_ok=True)
    study.trials_dataframe().to_csv(WORK_DIR / "trials_latest.csv", index=False)


def save_training(model, optimizer, scheduler, scaler, tag, params,
                  completed_epochs, epochs, steps_per_epoch):
    CHECKPOINT["training"] = dict(
        tag=tag, params=dict(params or {}), completed_epochs=completed_epochs,
        epochs=epochs, steps_per_epoch=steps_per_epoch,
        # Frozen encoder weights are reloaded from MODEL_NAME on the next run.
        model={k: v for k, v in model.state_dict().items() if not k.startswith("encoder.")},
        optimizer=optimizer.state_dict(), scheduler=scheduler.state_dict(),
        scaler=scaler.state_dict(), rng=capture_rng()
    )
    save_latest()
    print(f"Saved {tag}: epoch {completed_epochs}/{epochs}", flush=True)

Loaded: /kaggle/working/checkpoint_latest.pt
Working checkpoint: /kaggle/working/checkpoint_latest.pt
Completed trials: 25 / 25

In [8]:
# ถ้าใช้ไฟล์ .rar ที่อัปโหลดมาโดยตรงใน Google Colab
# cell นี้จะ extract อัตโนมัติ
RAR_PATH = "/content/Thai Depression.rar"
EXTRACT_ROOT = "/content/thai_depression_extracted"

# รองรับกรณีอัปโหลดไฟล์ JSON ที่ extract มาแล้ว
TRAIN_JSON = "/kaggle/input/datasets/kmkimmy/thai-depression/Thai Depression/train.json"
VALID_JSON = "/kaggle/input/datasets/kmkimmy/thai-depression/Thai Depression/valid.json"
TEST_JSON = "/kaggle/input/datasets/kmkimmy/thai-depression/Thai Depression/test.json"

if not (
    os.path.exists(TRAIN_JSON)
    and os.path.exists(VALID_JSON)
    and os.path.exists(TEST_JSON)
):
    if os.path.exists(RAR_PATH):
        os.makedirs(EXTRACT_ROOT, exist_ok=True)

        if shutil.which("unrar") is None:
            raise RuntimeError(
                "ไม่พบคำสั่ง unrar กรุณารัน cell ติดตั้งด้านบนก่อน "
                "หรือ extract Thai Depression.rar แล้วอัปโหลด train.json, valid.json, test.json"
            )

        subprocess.run(
            ["unrar", "x", "-o+", RAR_PATH, EXTRACT_ROOT + "/"],
            check=True
        )

        TRAIN_JSON = os.path.join(EXTRACT_ROOT, "Thai Depression", "train.json")
        VALID_JSON = os.path.join(EXTRACT_ROOT, "Thai Depression", "valid.json")
        TEST_JSON = os.path.join(EXTRACT_ROOT, "Thai Depression", "test.json")

# fallback สำหรับ local/sandbox
if not os.path.exists(TRAIN_JSON):
    TRAIN_JSON = "/mnt/data/Thai_Depression_extracted/train.json"
    VALID_JSON = "/mnt/data/Thai_Depression_extracted/valid.json"
    TEST_JSON = "/mnt/data/Thai_Depression_extracted/test.json"

print("TRAIN JSON:", TRAIN_JSON)
print("VALID JSON:", VALID_JSON)
print("TEST JSON :", TEST_JSON)


def load_thai_depression_json(path):
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)

    frame = pd.DataFrame(data, columns=[TEXT_COLUMN, "label"])

    frame[TEXT_COLUMN] = frame[TEXT_COLUMN].astype(str).str.strip()
    frame["label"] = frame["label"].astype(str).str.strip()

    unknown = sorted(set(frame["label"]) - set(LABEL_COLUMNS))
    if unknown:
        raise ValueError(f"พบ label ที่ไม่รู้จัก: {unknown}")

    for label in LABEL_COLUMNS:
        frame[label] = (frame["label"] == label).astype(int)

    return frame[[TEXT_COLUMN] + LABEL_COLUMNS]


train_df = load_thai_depression_json(TRAIN_JSON)
val_df = load_thai_depression_json(VALID_JSON)
test_df = load_thai_depression_json(TEST_JSON)

print("TRAIN:", len(train_df))
print("VALIDATION:", len(val_df))
print("TEST:", len(test_df))

print("\nTRAIN LABEL DISTRIBUTION")
print(train_df[LABEL_COLUMNS].sum())

print("\nVALIDATION LABEL DISTRIBUTION")
print(val_df[LABEL_COLUMNS].sum())

print("\nTEST LABEL DISTRIBUTION")
print(test_df[LABEL_COLUMNS].sum())

print("\nLABEL CARDINALITY")
print("TRAIN")
print(train_df[LABEL_COLUMNS].sum(axis=1).value_counts().sort_index())
print("VALIDATION")
print(val_df[LABEL_COLUMNS].sum(axis=1).value_counts().sort_index())
print("TEST")
print(test_df[LABEL_COLUMNS].sum(axis=1).value_counts().sort_index())

TRAIN JSON: /kaggle/input/datasets/kmkimmy/thai-depression/Thai Depression/train.json
VALID JSON: /kaggle/input/datasets/kmkimmy/thai-depression/Thai Depression/valid.json
TEST JSON : /kaggle/input/datasets/kmkimmy/thai-depression/Thai Depression/test.json
TRAIN: 25077
VALIDATION: 3344
TEST: 5015

TRAIN LABEL DISTRIBUTION
depression       12837
no_depression    12240
dtype: int64

VALIDATION LABEL DISTRIBUTION
depression       1712
no_depression    1632
dtype: int64

TEST LABEL DISTRIBUTION
depression       2567
no_depression    2448
dtype: int64

LABEL CARDINALITY
TRAIN
1    25077
Name: count, dtype: int64
VALIDATION
1    3344
Name: count, dtype: int64
TEST
1    5015
Name: count, dtype: int64

In [9]:
# Thai Depression มี train/validation/test split มาให้แล้ว
# จึงไม่ split ใหม่ เพื่อรักษา protocol ของ dataset เดิม

assert len(train_df) > 0
assert len(val_df) > 0
assert len(test_df) > 0

assert (train_df[LABEL_COLUMNS].sum(axis=1) == 1).all()
assert (val_df[LABEL_COLUMNS].sum(axis=1) == 1).all()
assert (test_df[LABEL_COLUMNS].sum(axis=1) == 1).all()

print("ใช้ original dataset split โดยตรงเรียบร้อย")

ใช้ original dataset split โดยตรงเรียบร้อย

In [10]:
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/625 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

In [11]:
class EmotionDataset(Dataset):

    def __init__(self, df):

        self.texts = df[TEXT_COLUMN].tolist()

        self.labels = df[LABEL_COLUMNS].values.astype(np.float32)

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):

        text = str(self.texts[idx])

        labels = self.labels[idx]

        encoding = tokenizer(
            text,
            truncation=True,
            padding="max_length",
            max_length=MAX_LEN,
            return_tensors="pt"
        )

        return {
            "input_ids": encoding["input_ids"].squeeze(0),
            "attention_mask": encoding["attention_mask"].squeeze(0),
            "labels": torch.tensor(labels, dtype=torch.float)
        }
train_dataset = EmotionDataset(train_df)

val_dataset = EmotionDataset(val_df)

test_dataset = EmotionDataset(test_df)

In [12]:
train_loader = DataLoader(
    train_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True
)

train_eval_loader = DataLoader(
    train_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False
)

val_loader = DataLoader(
    val_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False
)

test_loader = DataLoader(
    test_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False
)

In [13]:
# pos_weight เดิมทำให้ recall สูง แต่ precision ตกได้
# จึงไม่ fix pos_weight ตายตัว แต่ให้ Optuna tune pos_weight_scale
# scale = 0.0 คือไม่ใช้ pos_weight
# scale = 1.0 คือใช้ pos_weight เต็มสูตร negative / positive

label_counts = train_df[LABEL_COLUMNS].sum().values.astype(np.float32)
total_samples = len(train_df)
neg_counts = total_samples - label_counts

pos_weights_raw = neg_counts / (label_counts + 1e-6)

pos_weights_raw = torch.tensor(
    pos_weights_raw,
    dtype=torch.float
).to(device)

def build_pos_weight(pos_weight_scale):
    pos_weight_scale = float(pos_weight_scale)

    weights = 1.0 + (pos_weights_raw - 1.0) * pos_weight_scale

    return weights.to(device)

print("LABEL COUNTS:", label_counts)
print("RAW POS WEIGHTS:", pos_weights_raw)
print("NO POS WEIGHT:", build_pos_weight(0.0))
print("HALF POS WEIGHT:", build_pos_weight(0.5))

LABEL COUNTS: [12837. 12240.]
RAW POS WEIGHTS: tensor([0.9535, 1.0488], device='cuda:0')
NO POS WEIGHT: tensor([1., 1.], device='cuda:0')
HALF POS WEIGHT: tensor([0.9767, 1.0244], device='cuda:0')

In [14]:
class AttentionPooling(nn.Module):

    def __init__(self, hidden_size):

        super().__init__()

        self.attention = nn.Sequential(
            nn.Linear(hidden_size, hidden_size),
            nn.Tanh(),
            nn.Linear(hidden_size, 1)
        )

    def forward(self, x, mask):

        scores = self.attention(x).squeeze(-1)

        scores = scores.masked_fill(mask == 0, torch.finfo(scores.dtype).min)

        weights = torch.softmax(scores, dim=1)

        pooled = torch.sum(
            x * weights.unsqueeze(-1),
            dim=1
        )

        return pooled

In [15]:
class EmotionModel(nn.Module):

    def __init__(
        self,
        depth=1,
        heads=2,
        attn_dropout=0.15,
        ff_dropout=0.15,
        ff_mult=2
    ):

        super().__init__()

        self.encoder = AutoModel.from_pretrained(
            MODEL_NAME
        )

        # Fixed Thai encoder: train เฉพาะ decoder + pooling + classifier
        for param in self.encoder.parameters():
            param.requires_grad = False

        hidden_size = self.encoder.config.hidden_size

        self.decoder = Decoder(
            dim=hidden_size,
            depth=depth,
            heads=heads,
            attn_dropout=attn_dropout,
            ff_dropout=ff_dropout,
            ff_mult=ff_mult
        )

        self.pooling = AttentionPooling(hidden_size)

        self.dropout = nn.Dropout(0.30)

        self.fc = nn.Linear(
            hidden_size,
            NUM_LABELS
        )

    def forward(self, input_ids, attention_mask):

        with torch.no_grad():
            outputs = self.encoder(
                input_ids=input_ids,
                attention_mask=attention_mask
            )

        x = outputs.last_hidden_state

        x = self.decoder(x)

        x = self.pooling(x, attention_mask)

        x = self.dropout(x)

        logits = self.fc(x)

        return logits

In [16]:
def optimize_thresholds(
    y_true,
    y_probs,
    min_thr=0.20,
    max_thr=0.80,
    step=0.005
):

    thresholds = np.arange(
        min_thr,
        max_thr + 1e-9,
        step
    )

    best_thresholds = []

    for i in range(NUM_LABELS):

        best_thr = 0.5
        best_score = -1
        best_precision = -1

        true_support = y_true[:, i].sum()

        for thr in thresholds:

            preds = (y_probs[:, i] >= thr).astype(int)

            score = f1_score(
                y_true[:, i],
                preds,
                zero_division=0
            )

            precision = precision_score(
                y_true[:, i],
                preds,
                zero_division=0
            )

            # ถ้า F1 เท่ากัน ให้เลือก threshold ที่ precision สูงกว่า
            # ช่วยแก้ปัญหา optimized เดิมที่ recall สูงแต่ precision ต่ำ
            if (score > best_score) or (
                np.isclose(score, best_score) and precision > best_precision
            ):

                best_score = score
                best_precision = precision
                best_thr = thr

        best_thresholds.append(best_thr)

    return np.array(best_thresholds)

In [17]:
def evaluate(model, loader, thresholds=None):

    model.eval()

    all_labels = []
    all_probs = []

    with torch.no_grad():

        for batch in loader:

            input_ids = batch["input_ids"].to(device)
            attention_mask = batch["attention_mask"].to(device)
            labels = batch["labels"].to(device)

            logits = model(
                input_ids,
                attention_mask
            )

            probs = torch.sigmoid(logits)

            all_probs.append(
                probs.cpu().numpy()
            )

            all_labels.append(
                labels.cpu().numpy()
            )

    all_probs = np.vstack(all_probs)
    all_labels = np.vstack(all_labels)

    if thresholds is None:
        thresholds = np.array([0.5] * NUM_LABELS)

    preds = (all_probs >= thresholds).astype(int)

    micro_f1 = f1_score(
        all_labels,
        preds,
        average="micro",
        zero_division=0
    )

    macro_f1 = f1_score(
        all_labels,
        preds,
        average="macro",
        zero_division=0
    )

    weighted_f1 = f1_score(
        all_labels,
        preds,
        average="weighted",
        zero_division=0
    )

    micro_precision = precision_score(
        all_labels,
        preds,
        average="micro",
        zero_division=0
    )

    macro_precision = precision_score(
        all_labels,
        preds,
        average="macro",
        zero_division=0
    )

    micro_recall = recall_score(
        all_labels,
        preds,
        average="micro",
        zero_division=0
    )

    macro_recall = recall_score(
        all_labels,
        preds,
        average="macro",
        zero_division=0
    )

    per_label_f1 = f1_score(
        all_labels,
        preds,
        average=None,
        zero_division=0
    )

    per_label_precision = precision_score(
        all_labels,
        preds,
        average=None,
        zero_division=0
    )

    per_label_recall = recall_score(
        all_labels,
        preds,
        average=None,
        zero_division=0
    )

    subset_accuracy = accuracy_score(
        all_labels,
        preds
    )

    h_loss = hamming_loss(
        all_labels,
        preds
    )

    return {
        "micro_f1": micro_f1,
        "macro_f1": macro_f1,
        "weighted_f1": weighted_f1,
        "micro_precision": micro_precision,
        "macro_precision": macro_precision,
        "micro_recall": micro_recall,
        "macro_recall": macro_recall,
        "per_label_f1": per_label_f1,
        "per_label_precision": per_label_precision,
        "per_label_recall": per_label_recall,
        "min_per_label_f1": float(np.min(per_label_f1)),
        "accuracy": subset_accuracy,
        "subset_accuracy": subset_accuracy,
        "hamming_loss": h_loss,
        "labels": all_labels,
        "preds": preds,
        "probs": all_probs
    }


def objective_score(result):
    # objective ใหม่:
    # - macro_f1 สำคัญที่สุด เพราะต้องชนะราย class
    # - micro_f1 ยังสำคัญ
    # - min_per_label_f1 กันไม่ให้ class ใด class หนึ่งต่ำ โดยเฉพาะ Disgust
    # - subset accuracy ช่วยให้ทายชุด label ตรงขึ้น
    return (
        0.45 * result["macro_f1"]
        + 0.25 * result["micro_f1"]
        + 0.20 * result["min_per_label_f1"]
        + 0.10 * result["subset_accuracy"]
    )

In [18]:
def train_model(
    model,
    train_loader,
    val_loader,
    lr,
    weight_decay,
    epochs=None,
    pos_weight_scale=0.0,
    label_smoothing=0.0,
    loss_name="bce",
    focal_gamma=2.0,
    verbose=True,
    checkpoint_tag=None,
    checkpoint_params=None
):

    if epochs is None:
        epochs = EPOCHS

    pos_weight = build_pos_weight(pos_weight_scale)

    bce_loss = nn.BCEWithLogitsLoss(
        pos_weight=pos_weight,
        reduction="none"
    )

    trainable_params = [p for p in model.parameters() if p.requires_grad]

    optimizer = torch.optim.AdamW(
        trainable_params,
        lr=lr,
        weight_decay=weight_decay
    )

    total_steps = len(train_loader) * epochs

    scheduler = get_linear_schedule_with_warmup(
        optimizer,
        num_warmup_steps=int(0.06 * total_steps),
        num_training_steps=total_steps
    )

    use_amp = device.type == "cuda"

    scaler = torch.amp.GradScaler("cuda",
        enabled=use_amp
    )

    start_epoch = 0
    saved = CHECKPOINT.get("training")
    if checkpoint_tag is not None and saved and saved["tag"] == checkpoint_tag:
        if (saved["params"] != dict(checkpoint_params or {})
                or saved["epochs"] != epochs
                or saved["steps_per_epoch"] != len(train_loader)):
            raise ValueError("Training parameters or dataset batch count differ from checkpoint")
        incompatible = model.load_state_dict(saved["model"], strict=False)
        if incompatible.unexpected_keys or any(
            not key.startswith("encoder.") for key in incompatible.missing_keys
        ):
            raise ValueError("Checkpoint does not match the trainable model")
        optimizer.load_state_dict(saved["optimizer"])
        scheduler.load_state_dict(saved["scheduler"])
        scaler.load_state_dict(saved["scaler"])
        restore_rng(saved["rng"])
        start_epoch = saved["completed_epochs"]
        if start_epoch < epochs:
            print(f"Resuming {checkpoint_tag}: next epoch {start_epoch + 1}/{epochs}")
        else:
            print(f"Resuming {checkpoint_tag}: all {epochs} epochs saved; continuing evaluation")
    elif checkpoint_tag is not None:
        save_training(model, optimizer, scheduler, scaler, checkpoint_tag,
                      checkpoint_params, 0, epochs, len(train_loader))

    for epoch in range(start_epoch, epochs):
        if session_expired():
            raise SessionTimeLimit()

        model.train()
        total_loss = 0

        loop = tqdm(
            train_loader,
            disable=not verbose
        )

        for batch in loop:

            input_ids = batch["input_ids"].to(device)
            attention_mask = batch["attention_mask"].to(device)
            labels = batch["labels"].to(device)

            if label_smoothing > 0:
                # smooth toward 0.5 for multi-label BCE
                labels_for_loss = labels * (1.0 - label_smoothing) + 0.5 * label_smoothing
            else:
                labels_for_loss = labels

            optimizer.zero_grad()

            with torch.amp.autocast("cuda", enabled=use_amp):

                logits = model(
                    input_ids,
                    attention_mask
                )

                loss_matrix = bce_loss(
                    logits,
                    labels_for_loss
                )

                if loss_name == "focal":
                    probs = torch.sigmoid(logits)
                    pt = probs * labels + (1 - probs) * (1 - labels)
                    focal_weight = (1 - pt).pow(focal_gamma)
                    loss = (focal_weight * loss_matrix).mean()
                else:
                    loss = loss_matrix.mean()

            scaler.scale(loss).backward()
            scaler.unscale_(optimizer)

            torch.nn.utils.clip_grad_norm_(
                trainable_params,
                1.0
            )

            scaler.step(optimizer)
            scaler.update()
            scheduler.step()

            total_loss += loss.item()

            if verbose:
                loop.set_description(
                    f"Epoch {epoch+1}/{epochs}"
                )

                loop.set_postfix(
                    loss=loss.item()
                )

        if verbose:

            val_raw = evaluate(
                model,
                val_loader
            )

            val_thresholds = optimize_thresholds(
                val_raw["labels"],
                val_raw["probs"]
            )

            val_result = evaluate(
                model,
                val_loader,
                val_thresholds
            )

            print("\n======================")
            print(f"Epoch {epoch+1}")
            print("======================")

            print(
                f"VAL SUBSET ACC : {val_result['subset_accuracy']:.4f}"
            )

            print(
                f"VAL MICRO P/R/F1: "
                f"{val_result['micro_precision']:.4f} / "
                f"{val_result['micro_recall']:.4f} / "
                f"{val_result['micro_f1']:.4f}"
            )

            print(
                f"VAL MACRO P/R/F1: "
                f"{val_result['macro_precision']:.4f} / "
                f"{val_result['macro_recall']:.4f} / "
                f"{val_result['macro_f1']:.4f}"
            )

            print(
                f"VAL MIN LABEL F1: {val_result['min_per_label_f1']:.4f}"
            )

            print(
                f"VAL WEIGHTED F1: {val_result['weighted_f1']:.4f}"
            )

            print(
                f"VAL HAMMING LOSS: {val_result['hamming_loss']:.4f}"
            )

        if checkpoint_tag is not None:
            save_training(model, optimizer, scheduler, scaler, checkpoint_tag,
                          checkpoint_params, epoch + 1, epochs, len(train_loader))

    return model

In [19]:
def objective(trial):

    # baseline trial จะถูก enqueue ไว้ก่อนหน้า
    depth = trial.suggest_int(
        "depth",
        1,
        3
    )

    heads = trial.suggest_categorical(
        "heads",
        [2, 4, 8]
    )

    # ลด dropout range จากเดิมที่สูงเกินไป เพราะเดิม optimized มีแนวโน้ม underfit / recall เยอะ precision ตก
    attn_dropout = trial.suggest_float(
        "attn_dropout",
        0.05,
        0.30
    )

    ff_dropout = trial.suggest_float(
        "ff_dropout",
        0.05,
        0.30
    )

    ff_mult = trial.suggest_int(
        "ff_mult",
        2,
        4
    )

    lr = trial.suggest_float(
        "lr",
        1e-5,
        1e-4,
        log=True
    )

    weight_decay = trial.suggest_float(
        "weight_decay",
        1e-6,
        1e-2,
        log=True
    )

    # จุดสำคัญ: ให้ Optuna เลือกว่าจะใช้ pos_weight แค่ไหน
    # ถ้า scale สูงเกินจะ recall สูงแต่ precision ลด
    pos_weight_scale = trial.suggest_float(
        "pos_weight_scale",
        0.0,
        0.60
    )

    label_smoothing = trial.suggest_float(
        "label_smoothing",
        0.0,
        0.04
    )

    loss_name = trial.suggest_categorical(
        "loss_name",
        ["bce", "focal"]
    )

    focal_gamma = trial.suggest_float(
        "focal_gamma",
        1.0,
        2.5
    )

    model = EmotionModel(
        depth=depth,
        heads=heads,
        attn_dropout=attn_dropout,
        ff_dropout=ff_dropout,
        ff_mult=ff_mult
    ).to(device)

    model = train_model(
        model,
        train_loader,
        val_loader,
        lr=lr,
        weight_decay=weight_decay,
        epochs=OPTUNA_EPOCHS,
        pos_weight_scale=pos_weight_scale,
        label_smoothing=label_smoothing,
        loss_name=loss_name,
        focal_gamma=focal_gamma,
        verbose=False,
        checkpoint_tag=f"trial:{trial.number}",
        checkpoint_params=dict(trial.params)
    )

    val_raw = evaluate(
        model,
        val_loader
    )

    thresholds = optimize_thresholds(
        val_raw["labels"],
        val_raw["probs"]
    )

    val_result = evaluate(
        model,
        val_loader,
        thresholds
    )

    score = objective_score(val_result)

    trial.set_user_attr("val_macro_f1", float(val_result["macro_f1"]))
    trial.set_user_attr("val_micro_f1", float(val_result["micro_f1"]))
    trial.set_user_attr("val_min_per_label_f1", float(val_result["min_per_label_f1"]))
    trial.set_user_attr("val_subset_accuracy", float(val_result["subset_accuracy"]))
    trial.set_user_attr("thresholds", thresholds.tolist())

    return score

In [20]:
# Resume Optuna and the active trial
if not study.trials:
    study.enqueue_trial({
        "depth": 1, "heads": 2,
        "attn_dropout": 0.20, "ff_dropout": 0.20,
        "ff_mult": 2, "lr": 2e-5, "weight_decay": 1e-2,
        "pos_weight_scale": 0.0, "label_smoothing": 0.0,
        "loss_name": "bce", "focal_gamma": 2.0
    })
    save_latest()

try:
    while len(study.get_trials(states=[optuna.trial.TrialState.COMPLETE])) < N_TRIALS:
        if session_expired():
            raise SessionTimeLimit()
        trial = CHECKPOINT["active_trial"]
        if trial is None:
            trial = study.ask()
            CHECKPOINT["active_trial"] = trial
            CHECKPOINT["training"] = None
            save_latest()
        print("Trial:", trial.number, "parameters:", trial.params, flush=True)
        score = objective(trial)
        study.tell(trial, score)
        CHECKPOINT["active_trial"] = None
        CHECKPOINT["training"] = None
        save_latest()
        print(f"Trial {trial.number} complete: {score:.6f}", flush=True)
except SessionTimeLimit:
    SESSION_STOPPED = True
    print("Session budget reached. The latest epoch is saved; final training is skipped.")

SEARCH_COMPLETE = len(study.get_trials(states=[optuna.trial.TrialState.COMPLETE])) >= N_TRIALS
print("Completed trials:", len(study.get_trials(states=[optuna.trial.TrialState.COMPLETE])), "/", N_TRIALS)

Completed trials: 25 / 25

In [21]:
if SEARCH_COMPLETE and not SESSION_STOPPED:
    print("\n======================")
    print("BEST PARAMETERS")
    print("======================")

    print(study.best_params)

    print("\n======================")
    print("BEST TRIAL VALIDATION ATTRS")
    print("======================")

    print("objective_score:", study.best_value)
    print("val_macro_f1:", study.best_trial.user_attrs.get("val_macro_f1"))
    print("val_micro_f1:", study.best_trial.user_attrs.get("val_micro_f1"))
    print("val_min_per_label_f1:", study.best_trial.user_attrs.get("val_min_per_label_f1"))
    print("val_subset_accuracy:", study.best_trial.user_attrs.get("val_subset_accuracy"))

    best_params = study.best_params

======================
BEST PARAMETERS
======================
{'depth': 2, 'heads': 8, 'attn_dropout': 0.18915726849602893, 'ff_dropout': 0.23960675619881897, 'ff_mult': 4, 'lr': 9.77129136506405e-05, 'weight_decay': 1.092580982528725e-05, 'pos_weight_scale': 0.058881624710698036, 'label_smoothing': 0.036311574679891497, 'loss_name': 'focal', 'focal_gamma': 1.5343612322754008}

======================
BEST TRIAL VALIDATION ATTRS
======================
objective_score: 0.7916690150643318
val_macro_f1: 0.7971564636171307
val_micro_f1: 0.7974463145676146
val_min_per_label_f1: 0.7875523638539796
val_subset_accuracy: 0.7607655502392344

In [22]:
if SEARCH_COMPLETE and not SESSION_STOPPED:
    final_model = EmotionModel(
        depth=best_params["depth"],
        heads=best_params["heads"],
        attn_dropout=best_params["attn_dropout"],
        ff_dropout=best_params["ff_dropout"],
        ff_mult=best_params["ff_mult"]
    ).to(device)

model.safetensors:   0%|          | 0.00/714M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: bert-base-multilingual-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [23]:
if SEARCH_COMPLETE and not SESSION_STOPPED:
    try:
        final_model = train_model(
            final_model,
            train_loader,
            val_loader,
            lr=best_params["lr"],
            weight_decay=best_params["weight_decay"],
            epochs=EPOCHS,
            pos_weight_scale=best_params["pos_weight_scale"],
            label_smoothing=best_params["label_smoothing"],
            loss_name=best_params["loss_name"],
            focal_gamma=best_params["focal_gamma"],
            verbose=True,
            checkpoint_tag="final",
            checkpoint_params=dict(best_params)
        )
        FINAL_TRAINING_COMPLETE = True
    except SessionTimeLimit:
        SESSION_STOPPED = True
        print("Final training paused; latest epoch saved.")

Saved final: epoch 0/100

Epoch 1/100: 100%|██████████| 392/392 [01:11<00:00,  5.49it/s, loss=0.203]

======================
Epoch 1
======================
VAL SUBSET ACC : 0.4459
VAL MICRO P/R/F1: 0.6115 / 0.8723 / 0.7190
VAL MACRO P/R/F1: 0.6114 / 0.8716 / 0.7185
VAL MIN LABEL F1: 0.7069
VAL WEIGHTED F1: 0.7188
VAL HAMMING LOSS: 0.3409
Saved final: epoch 1/100

Epoch 2/100: 100%|██████████| 392/392 [01:18<00:00,  4.97it/s, loss=0.21]

======================
Epoch 2
======================
VAL SUBSET ACC : 0.5260
VAL MICRO P/R/F1: 0.6470 / 0.8687 / 0.7416
VAL MACRO P/R/F1: 0.6466 / 0.8681 / 0.7411
VAL MIN LABEL F1: 0.7252
VAL WEIGHTED F1: 0.7415
VAL HAMMING LOSS: 0.3026
Saved final: epoch 2/100

Epoch 3/100: 100%|██████████| 392/392 [01:18<00:00,  4.99it/s, loss=0.185]

======================
Epoch 3
======================
VAL SUBSET ACC : 0.5760
VAL MICRO P/R/F1: 0.6709 / 0.8645 / 0.7555
VAL MACRO P/R/F1: 0.6706 / 0.8640 / 0.7551
VAL MIN LABEL F1: 0.7406
VAL WEIGHTED F1: 0.7554
VAL HAMMING LOSS: 0.2798
Saved final: epoch 3/100

Epoch 4/100: 100%|██████████| 392/392 [01:18<00:00,  4.99it/s, loss=0.172]

======================
Epoch 4
======================
VAL SUBSET ACC : 0.5733
VAL MICRO P/R/F1: 0.6735 / 0.8801 / 0.7630
VAL MACRO P/R/F1: 0.6739 / 0.8793 / 0.7626
VAL MIN LABEL F1: 0.7540
VAL WEIGHTED F1: 0.7628
VAL HAMMING LOSS: 0.2733
Saved final: epoch 4/100

Epoch 5/100: 100%|██████████| 392/392 [01:18<00:00,  4.99it/s, loss=0.173]

======================
Epoch 5
======================
VAL SUBSET ACC : 0.6633
VAL MICRO P/R/F1: 0.7150 / 0.8448 / 0.7745
VAL MACRO P/R/F1: 0.7149 / 0.8446 / 0.7743
VAL MIN LABEL F1: 0.7673
VAL WEIGHTED F1: 0.7745
VAL HAMMING LOSS: 0.2460
Saved final: epoch 5/100

Epoch 6/100: 100%|██████████| 392/392 [01:18<00:00,  4.99it/s, loss=0.169]

======================
Epoch 6
======================
VAL SUBSET ACC : 0.6687
VAL MICRO P/R/F1: 0.7201 / 0.8526 / 0.7808
VAL MACRO P/R/F1: 0.7201 / 0.8520 / 0.7804
VAL MIN LABEL F1: 0.7696
VAL WEIGHTED F1: 0.7806
VAL HAMMING LOSS: 0.2394
Saved final: epoch 6/100

Epoch 7/100: 100%|██████████| 392/392 [01:18<00:00,  4.99it/s, loss=0.146]

======================
Epoch 7
======================
VAL SUBSET ACC : 0.6426
VAL MICRO P/R/F1: 0.7097 / 0.8738 / 0.7833
VAL MACRO P/R/F1: 0.7101 / 0.8730 / 0.7828
VAL MIN LABEL F1: 0.7735
VAL WEIGHTED F1: 0.7830
VAL HAMMING LOSS: 0.2418
Saved final: epoch 7/100

Epoch 8/100: 100%|██████████| 392/392 [01:18<00:00,  5.00it/s, loss=0.158]

======================
Epoch 8
======================
VAL SUBSET ACC : 0.6875
VAL MICRO P/R/F1: 0.7305 / 0.8469 / 0.7844
VAL MACRO P/R/F1: 0.7309 / 0.8463 / 0.7841
VAL MIN LABEL F1: 0.7772
VAL WEIGHTED F1: 0.7842
VAL HAMMING LOSS: 0.2328
Saved final: epoch 8/100

Epoch 9/100: 100%|██████████| 392/392 [01:18<00:00,  4.99it/s, loss=0.126]

======================
Epoch 9
======================
VAL SUBSET ACC : 0.6666
VAL MICRO P/R/F1: 0.7222 / 0.8666 / 0.7878
VAL MACRO P/R/F1: 0.7228 / 0.8660 / 0.7875
VAL MIN LABEL F1: 0.7817
VAL WEIGHTED F1: 0.7877
VAL HAMMING LOSS: 0.2334
Saved final: epoch 9/100

Epoch 10/100: 100%|██████████| 392/392 [01:18<00:00,  4.99it/s, loss=0.128]

======================
Epoch 10
======================
VAL SUBSET ACC : 0.6438
VAL MICRO P/R/F1: 0.7128 / 0.8840 / 0.7892
VAL MACRO P/R/F1: 0.7136 / 0.8832 / 0.7889
VAL MIN LABEL F1: 0.7831
VAL WEIGHTED F1: 0.7890
VAL HAMMING LOSS: 0.2361
Saved final: epoch 10/100

Epoch 11/100: 100%|██████████| 392/392 [01:18<00:00,  5.00it/s, loss=0.151]

======================
Epoch 11
======================
VAL SUBSET ACC : 0.7028
VAL MICRO P/R/F1: 0.7423 / 0.8562 / 0.7952
VAL MACRO P/R/F1: 0.7424 / 0.8557 / 0.7949
VAL MIN LABEL F1: 0.7888
VAL WEIGHTED F1: 0.7951
VAL HAMMING LOSS: 0.2205
Saved final: epoch 11/100

Epoch 12/100: 100%|██████████| 392/392 [01:18<00:00,  4.99it/s, loss=0.151]

======================
Epoch 12
======================
VAL SUBSET ACC : 0.6974
VAL MICRO P/R/F1: 0.7388 / 0.8562 / 0.7932
VAL MACRO P/R/F1: 0.7396 / 0.8553 / 0.7927
VAL MIN LABEL F1: 0.7831
VAL WEIGHTED F1: 0.7929
VAL HAMMING LOSS: 0.2232
Saved final: epoch 12/100

Epoch 13/100: 100%|██████████| 392/392 [01:18<00:00,  4.97it/s, loss=0.198]

======================
Epoch 13
======================
VAL SUBSET ACC : 0.7249
VAL MICRO P/R/F1: 0.7534 / 0.8403 / 0.7945
VAL MACRO P/R/F1: 0.7540 / 0.8397 / 0.7942
VAL MIN LABEL F1: 0.7890
VAL WEIGHTED F1: 0.7943
VAL HAMMING LOSS: 0.2174
Saved final: epoch 13/100

Epoch 14/100: 100%|██████████| 392/392 [01:18<00:00,  4.99it/s, loss=0.158]

======================
Epoch 14
======================
VAL SUBSET ACC : 0.7162
VAL MICRO P/R/F1: 0.7507 / 0.8544 / 0.7992
VAL MACRO P/R/F1: 0.7508 / 0.8538 / 0.7988
VAL MIN LABEL F1: 0.7906
VAL WEIGHTED F1: 0.7990
VAL HAMMING LOSS: 0.2147
Saved final: epoch 14/100

Epoch 15/100: 100%|██████████| 392/392 [01:18<00:00,  4.99it/s, loss=0.101]

======================
Epoch 15
======================
VAL SUBSET ACC : 0.7028
VAL MICRO P/R/F1: 0.7411 / 0.8508 / 0.7921
VAL MACRO P/R/F1: 0.7418 / 0.8499 / 0.7916
VAL MIN LABEL F1: 0.7806
VAL WEIGHTED F1: 0.7918
VAL HAMMING LOSS: 0.2232
Saved final: epoch 15/100

Epoch 16/100: 100%|██████████| 392/392 [01:18<00:00,  4.99it/s, loss=0.133]

======================
Epoch 16
======================
VAL SUBSET ACC : 0.6612
VAL MICRO P/R/F1: 0.7243 / 0.8900 / 0.7986
VAL MACRO P/R/F1: 0.7243 / 0.8899 / 0.7985
VAL MIN LABEL F1: 0.7857
VAL WEIGHTED F1: 0.7988
VAL HAMMING LOSS: 0.2244
Saved final: epoch 16/100

Epoch 17/100: 100%|██████████| 392/392 [01:18<00:00,  5.00it/s, loss=0.14]

======================
Epoch 17
======================
VAL SUBSET ACC : 0.6956
VAL MICRO P/R/F1: 0.7378 / 0.8565 / 0.7927
VAL MACRO P/R/F1: 0.7386 / 0.8554 / 0.7919
VAL MIN LABEL F1: 0.7789
VAL WEIGHTED F1: 0.7923
VAL HAMMING LOSS: 0.2240
Saved final: epoch 17/100

Epoch 18/100: 100%|██████████| 392/392 [01:18<00:00,  4.99it/s, loss=0.106]

======================
Epoch 18
======================
VAL SUBSET ACC : 0.7342
VAL MICRO P/R/F1: 0.7617 / 0.8499 / 0.8034
VAL MACRO P/R/F1: 0.7615 / 0.8494 / 0.8030
VAL MIN LABEL F1: 0.7923
VAL WEIGHTED F1: 0.8033
VAL HAMMING LOSS: 0.2080
Saved final: epoch 18/100

Epoch 19/100: 100%|██████████| 392/392 [01:18<00:00,  4.98it/s, loss=0.0965]

======================
Epoch 19
======================
VAL SUBSET ACC : 0.7458
VAL MICRO P/R/F1: 0.7662 / 0.8331 / 0.7983
VAL MACRO P/R/F1: 0.7671 / 0.8324 / 0.7978
VAL MIN LABEL F1: 0.7890
VAL WEIGHTED F1: 0.7980
VAL HAMMING LOSS: 0.2105
Saved final: epoch 19/100

Epoch 20/100: 100%|██████████| 392/392 [01:18<00:00,  4.98it/s, loss=0.098]

======================
Epoch 20
======================
VAL SUBSET ACC : 0.6600
VAL MICRO P/R/F1: 0.7219 / 0.8825 / 0.7941
VAL MACRO P/R/F1: 0.7223 / 0.8817 / 0.7937
VAL MIN LABEL F1: 0.7843
VAL WEIGHTED F1: 0.7939
VAL HAMMING LOSS: 0.2288
Saved final: epoch 20/100

Epoch 21/100: 100%|██████████| 392/392 [01:18<00:00,  5.00it/s, loss=0.14]

======================
Epoch 21
======================
VAL SUBSET ACC : 0.7048
VAL MICRO P/R/F1: 0.7436 / 0.8562 / 0.7959
VAL MACRO P/R/F1: 0.7436 / 0.8555 / 0.7955
VAL MIN LABEL F1: 0.7835
VAL WEIGHTED F1: 0.7957
VAL HAMMING LOSS: 0.2195
Saved final: epoch 21/100

Epoch 22/100: 100%|██████████| 392/392 [01:18<00:00,  5.00it/s, loss=0.12]

======================
Epoch 22
======================
VAL SUBSET ACC : 0.7297
VAL MICRO P/R/F1: 0.7576 / 0.8448 / 0.7988
VAL MACRO P/R/F1: 0.7578 / 0.8442 / 0.7984
VAL MIN LABEL F1: 0.7884
VAL WEIGHTED F1: 0.7986
VAL HAMMING LOSS: 0.2128
Saved final: epoch 22/100

Epoch 23/100: 100%|██████████| 392/392 [01:18<00:00,  4.98it/s, loss=0.111]

======================
Epoch 23
======================
VAL SUBSET ACC : 0.7195
VAL MICRO P/R/F1: 0.7529 / 0.8547 / 0.8006
VAL MACRO P/R/F1: 0.7536 / 0.8539 / 0.8001
VAL MIN LABEL F1: 0.7909
VAL WEIGHTED F1: 0.8003
VAL HAMMING LOSS: 0.2129
Saved final: epoch 23/100

Epoch 24/100: 100%|██████████| 392/392 [01:18<00:00,  4.98it/s, loss=0.0954]

======================
Epoch 24
======================
VAL SUBSET ACC : 0.7156
VAL MICRO P/R/F1: 0.7503 / 0.8544 / 0.7989
VAL MACRO P/R/F1: 0.7500 / 0.8538 / 0.7985
VAL MIN LABEL F1: 0.7852
VAL WEIGHTED F1: 0.7988
VAL HAMMING LOSS: 0.2150
Saved final: epoch 24/100

Epoch 25/100: 100%|██████████| 392/392 [01:18<00:00,  4.98it/s, loss=0.132]

======================
Epoch 25
======================
VAL SUBSET ACC : 0.7033
VAL MICRO P/R/F1: 0.7444 / 0.8639 / 0.7997
VAL MACRO P/R/F1: 0.7449 / 0.8641 / 0.7997
VAL MIN LABEL F1: 0.7877
VAL WEIGHTED F1: 0.8000
VAL HAMMING LOSS: 0.2164
Saved final: epoch 25/100

Epoch 26/100: 100%|██████████| 392/392 [01:18<00:00,  4.98it/s, loss=0.132]

======================
Epoch 26
======================
VAL SUBSET ACC : 0.7617
VAL MICRO P/R/F1: 0.7762 / 0.8269 / 0.8008
VAL MACRO P/R/F1: 0.7793 / 0.8256 / 0.7999
VAL MIN LABEL F1: 0.7887
VAL WEIGHTED F1: 0.8002
VAL HAMMING LOSS: 0.2057
Saved final: epoch 26/100

Epoch 27/100: 100%|██████████| 392/392 [01:18<00:00,  5.00it/s, loss=0.167]

======================
Epoch 27
======================
VAL SUBSET ACC : 0.7019
VAL MICRO P/R/F1: 0.7432 / 0.8630 / 0.7987
VAL MACRO P/R/F1: 0.7442 / 0.8620 / 0.7979
VAL MIN LABEL F1: 0.7843
VAL WEIGHTED F1: 0.7982
VAL HAMMING LOSS: 0.2176
Saved final: epoch 27/100

Epoch 28/100: 100%|██████████| 392/392 [01:18<00:00,  5.00it/s, loss=0.0856]

======================
Epoch 28
======================
VAL SUBSET ACC : 0.7153
VAL MICRO P/R/F1: 0.7500 / 0.8541 / 0.7987
VAL MACRO P/R/F1: 0.7510 / 0.8533 / 0.7982
VAL MIN LABEL F1: 0.7902
VAL WEIGHTED F1: 0.7984
VAL HAMMING LOSS: 0.2153
Saved final: epoch 28/100

Epoch 29/100: 100%|██████████| 392/392 [01:18<00:00,  5.00it/s, loss=0.0761]

======================
Epoch 29
======================
VAL SUBSET ACC : 0.7001
VAL MICRO P/R/F1: 0.7410 / 0.8583 / 0.7953
VAL MACRO P/R/F1: 0.7407 / 0.8578 / 0.7949
VAL MIN LABEL F1: 0.7813
VAL WEIGHTED F1: 0.7953
VAL HAMMING LOSS: 0.2208
Saved final: epoch 29/100

Epoch 30/100: 100%|██████████| 392/392 [01:18<00:00,  4.99it/s, loss=0.0725]

======================
Epoch 30
======================
VAL SUBSET ACC : 0.7028
VAL MICRO P/R/F1: 0.7429 / 0.8589 / 0.7967
VAL MACRO P/R/F1: 0.7430 / 0.8581 / 0.7962
VAL MIN LABEL F1: 0.7846
VAL WEIGHTED F1: 0.7964
VAL HAMMING LOSS: 0.2192
Saved final: epoch 30/100

Epoch 31/100: 100%|██████████| 392/392 [01:18<00:00,  5.00it/s, loss=0.115]

======================
Epoch 31
======================
VAL SUBSET ACC : 0.7309
VAL MICRO P/R/F1: 0.7583 / 0.8445 / 0.7991
VAL MACRO P/R/F1: 0.7586 / 0.8436 / 0.7984
VAL MIN LABEL F1: 0.7836
VAL WEIGHTED F1: 0.7987
VAL HAMMING LOSS: 0.2123
Saved final: epoch 31/100

Epoch 32/100: 100%|██████████| 392/392 [01:18<00:00,  5.00it/s, loss=0.0919]

======================
Epoch 32
======================
VAL SUBSET ACC : 0.7443
VAL MICRO P/R/F1: 0.7644 / 0.8295 / 0.7956
VAL MACRO P/R/F1: 0.7651 / 0.8287 / 0.7950
VAL MIN LABEL F1: 0.7831
VAL WEIGHTED F1: 0.7953
VAL HAMMING LOSS: 0.2131
Saved final: epoch 32/100

Epoch 33/100: 100%|██████████| 392/392 [01:18<00:00,  4.99it/s, loss=0.0476]

======================
Epoch 33
======================
VAL SUBSET ACC : 0.7045
VAL MICRO P/R/F1: 0.7426 / 0.8526 / 0.7938
VAL MACRO P/R/F1: 0.7424 / 0.8522 / 0.7935
VAL MIN LABEL F1: 0.7827
VAL WEIGHTED F1: 0.7938
VAL HAMMING LOSS: 0.2214
Saved final: epoch 33/100

Epoch 34/100: 100%|██████████| 392/392 [01:18<00:00,  5.00it/s, loss=0.0431]

======================
Epoch 34
======================
VAL SUBSET ACC : 0.6917
VAL MICRO P/R/F1: 0.7375 / 0.8660 / 0.7966
VAL MACRO P/R/F1: 0.7373 / 0.8658 / 0.7964
VAL MIN LABEL F1: 0.7874
VAL WEIGHTED F1: 0.7966
VAL HAMMING LOSS: 0.2211
Saved final: epoch 34/100

Epoch 35/100: 100%|██████████| 392/392 [01:18<00:00,  4.99it/s, loss=0.0717]

======================
Epoch 35
======================
VAL SUBSET ACC : 0.7210
VAL MICRO P/R/F1: 0.7514 / 0.8433 / 0.7947
VAL MACRO P/R/F1: 0.7552 / 0.8418 / 0.7936
VAL MIN LABEL F1: 0.7806
VAL WEIGHTED F1: 0.7939
VAL HAMMING LOSS: 0.2179
Saved final: epoch 35/100

Epoch 36/100: 100%|██████████| 392/392 [01:18<00:00,  4.99it/s, loss=0.0537]

======================
Epoch 36
======================
VAL SUBSET ACC : 0.7057
VAL MICRO P/R/F1: 0.7439 / 0.8547 / 0.7954
VAL MACRO P/R/F1: 0.7455 / 0.8535 / 0.7946
VAL MIN LABEL F1: 0.7826
VAL WEIGHTED F1: 0.7949
VAL HAMMING LOSS: 0.2198
Saved final: epoch 36/100

Epoch 37/100: 100%|██████████| 392/392 [01:18<00:00,  5.00it/s, loss=0.0892]

======================
Epoch 37
======================
VAL SUBSET ACC : 0.7629
VAL MICRO P/R/F1: 0.7734 / 0.8092 / 0.7909
VAL MACRO P/R/F1: 0.7743 / 0.8083 / 0.7902
VAL MIN LABEL F1: 0.7786
VAL WEIGHTED F1: 0.7905
VAL HAMMING LOSS: 0.2140
Saved final: epoch 37/100

Epoch 38/100: 100%|██████████| 392/392 [01:18<00:00,  5.00it/s, loss=0.0353]

======================
Epoch 38
======================
VAL SUBSET ACC : 0.7183
VAL MICRO P/R/F1: 0.7503 / 0.8466 / 0.7956
VAL MACRO P/R/F1: 0.7511 / 0.8458 / 0.7950
VAL MIN LABEL F1: 0.7849
VAL WEIGHTED F1: 0.7953
VAL HAMMING LOSS: 0.2176
Saved final: epoch 38/100

Epoch 39/100: 100%|██████████| 392/392 [01:18<00:00,  5.01it/s, loss=0.0435]

======================
Epoch 39
======================
VAL SUBSET ACC : 0.7575
VAL MICRO P/R/F1: 0.7711 / 0.8170 / 0.7934
VAL MACRO P/R/F1: 0.7714 / 0.8162 / 0.7927
VAL MIN LABEL F1: 0.7782
VAL WEIGHTED F1: 0.7930
VAL HAMMING LOSS: 0.2128
Saved final: epoch 39/100

Epoch 40/100: 100%|██████████| 392/392 [01:18<00:00,  5.00it/s, loss=0.0483]

======================
Epoch 40
======================
VAL SUBSET ACC : 0.7207
VAL MICRO P/R/F1: 0.7523 / 0.8484 / 0.7975
VAL MACRO P/R/F1: 0.7527 / 0.8474 / 0.7967
VAL MIN LABEL F1: 0.7816
VAL WEIGHTED F1: 0.7970
VAL HAMMING LOSS: 0.2155
Saved final: epoch 40/100

Epoch 41/100: 100%|██████████| 392/392 [01:18<00:00,  4.98it/s, loss=0.0732]

======================
Epoch 41
======================
VAL SUBSET ACC : 0.7473
VAL MICRO P/R/F1: 0.7668 / 0.8310 / 0.7976
VAL MACRO P/R/F1: 0.7687 / 0.8297 / 0.7965
VAL MIN LABEL F1: 0.7805
VAL WEIGHTED F1: 0.7969
VAL HAMMING LOSS: 0.2108
Saved final: epoch 41/100

Epoch 42/100: 100%|██████████| 392/392 [01:18<00:00,  5.00it/s, loss=0.0485]

======================
Epoch 42
======================
VAL SUBSET ACC : 0.7611
VAL MICRO P/R/F1: 0.7737 / 0.8170 / 0.7948
VAL MACRO P/R/F1: 0.7760 / 0.8157 / 0.7938
VAL MIN LABEL F1: 0.7799
VAL WEIGHTED F1: 0.7941
VAL HAMMING LOSS: 0.2110
Saved final: epoch 42/100

Epoch 43/100: 100%|██████████| 392/392 [01:18<00:00,  5.00it/s, loss=0.0452]

======================
Epoch 43
======================
VAL SUBSET ACC : 0.7001
VAL MICRO P/R/F1: 0.7417 / 0.8612 / 0.7970
VAL MACRO P/R/F1: 0.7414 / 0.8607 / 0.7966
VAL MIN LABEL F1: 0.7820
VAL WEIGHTED F1: 0.7969
VAL HAMMING LOSS: 0.2193
Saved final: epoch 43/100

Epoch 44/100: 100%|██████████| 392/392 [01:18<00:00,  5.00it/s, loss=0.016]

======================
Epoch 44
======================
VAL SUBSET ACC : 0.7117
VAL MICRO P/R/F1: 0.7459 / 0.8463 / 0.7929
VAL MACRO P/R/F1: 0.7464 / 0.8454 / 0.7923
VAL MIN LABEL F1: 0.7804
VAL WEIGHTED F1: 0.7926
VAL HAMMING LOSS: 0.2210
Saved final: epoch 44/100

Epoch 45/100: 100%|██████████| 392/392 [01:18<00:00,  5.00it/s, loss=0.0135]

======================
Epoch 45
======================
VAL SUBSET ACC : 0.7096
VAL MICRO P/R/F1: 0.7461 / 0.8532 / 0.7960
VAL MACRO P/R/F1: 0.7463 / 0.8524 / 0.7954
VAL MIN LABEL F1: 0.7827
VAL WEIGHTED F1: 0.7957
VAL HAMMING LOSS: 0.2186
Saved final: epoch 45/100

Epoch 46/100: 100%|██████████| 392/392 [01:18<00:00,  4.99it/s, loss=0.029]

======================
Epoch 46
======================
VAL SUBSET ACC : 0.6651
VAL MICRO P/R/F1: 0.7240 / 0.8786 / 0.7938
VAL MACRO P/R/F1: 0.7238 / 0.8782 / 0.7936
VAL MIN LABEL F1: 0.7834
VAL WEIGHTED F1: 0.7938
VAL HAMMING LOSS: 0.2282
Saved final: epoch 46/100

Epoch 47/100: 100%|██████████| 392/392 [01:18<00:00,  5.00it/s, loss=0.049]

======================
Epoch 47
======================
VAL SUBSET ACC : 0.7189
VAL MICRO P/R/F1: 0.7495 / 0.8412 / 0.7927
VAL MACRO P/R/F1: 0.7502 / 0.8402 / 0.7920
VAL MIN LABEL F1: 0.7784
VAL WEIGHTED F1: 0.7923
VAL HAMMING LOSS: 0.2199
Saved final: epoch 47/100

Epoch 48/100: 100%|██████████| 392/392 [01:18<00:00,  4.99it/s, loss=0.0555]

======================
Epoch 48
======================
VAL SUBSET ACC : 0.6761
VAL MICRO P/R/F1: 0.7292 / 0.8720 / 0.7942
VAL MACRO P/R/F1: 0.7294 / 0.8712 / 0.7937
VAL MIN LABEL F1: 0.7829
VAL WEIGHTED F1: 0.7940
VAL HAMMING LOSS: 0.2259
Saved final: epoch 48/100

Epoch 49/100: 100%|██████████| 392/392 [01:18<00:00,  4.98it/s, loss=0.0343]

======================
Epoch 49
======================
VAL SUBSET ACC : 0.6812
VAL MICRO P/R/F1: 0.7318 / 0.8699 / 0.7949
VAL MACRO P/R/F1: 0.7316 / 0.8696 / 0.7946
VAL MIN LABEL F1: 0.7831
VAL WEIGHTED F1: 0.7949
VAL HAMMING LOSS: 0.2244
Saved final: epoch 49/100

Epoch 50/100: 100%|██████████| 392/392 [01:18<00:00,  4.99it/s, loss=0.0688]

======================
Epoch 50
======================
VAL SUBSET ACC : 0.7126
VAL MICRO P/R/F1: 0.7464 / 0.8460 / 0.7931
VAL MACRO P/R/F1: 0.7466 / 0.8451 / 0.7924
VAL MIN LABEL F1: 0.7778
VAL WEIGHTED F1: 0.7927
VAL HAMMING LOSS: 0.2207
Saved final: epoch 50/100

Epoch 51/100: 100%|██████████| 392/392 [01:18<00:00,  4.99it/s, loss=0.0189]

======================
Epoch 51
======================
VAL SUBSET ACC : 0.6905
VAL MICRO P/R/F1: 0.7379 / 0.8714 / 0.7991
VAL MACRO P/R/F1: 0.7377 / 0.8709 / 0.7987
VAL MIN LABEL F1: 0.7867
VAL WEIGHTED F1: 0.7990
VAL HAMMING LOSS: 0.2190
Saved final: epoch 51/100

Epoch 52/100: 100%|██████████| 392/392 [01:18<00:00,  4.99it/s, loss=0.028]

======================
Epoch 52
======================
VAL SUBSET ACC : 0.7228
VAL MICRO P/R/F1: 0.7529 / 0.8445 / 0.7961
VAL MACRO P/R/F1: 0.7552 / 0.8431 / 0.7949
VAL MIN LABEL F1: 0.7795
VAL WEIGHTED F1: 0.7953
VAL HAMMING LOSS: 0.2164
Saved final: epoch 52/100

Epoch 53/100: 100%|██████████| 392/392 [01:18<00:00,  4.99it/s, loss=0.0238]

======================
Epoch 53
======================
VAL SUBSET ACC : 0.7019
VAL MICRO P/R/F1: 0.7426 / 0.8600 / 0.7970
VAL MACRO P/R/F1: 0.7424 / 0.8598 / 0.7967
VAL MIN LABEL F1: 0.7811
VAL WEIGHTED F1: 0.7971
VAL HAMMING LOSS: 0.2190
Saved final: epoch 53/100

Epoch 54/100: 100%|██████████| 392/392 [01:18<00:00,  5.00it/s, loss=0.0224]

======================
Epoch 54
======================
VAL SUBSET ACC : 0.6986
VAL MICRO P/R/F1: 0.7401 / 0.8583 / 0.7948
VAL MACRO P/R/F1: 0.7397 / 0.8577 / 0.7943
VAL MIN LABEL F1: 0.7799
VAL WEIGHTED F1: 0.7947
VAL HAMMING LOSS: 0.2216
Saved final: epoch 54/100

Epoch 55/100: 100%|██████████| 392/392 [01:18<00:00,  5.01it/s, loss=0.0506]

======================
Epoch 55
======================
VAL SUBSET ACC : 0.7159
VAL MICRO P/R/F1: 0.7497 / 0.8511 / 0.7972
VAL MACRO P/R/F1: 0.7497 / 0.8503 / 0.7966
VAL MIN LABEL F1: 0.7830
VAL WEIGHTED F1: 0.7969
VAL HAMMING LOSS: 0.2165
Saved final: epoch 55/100

Epoch 56/100: 100%|██████████| 392/392 [01:18<00:00,  5.00it/s, loss=0.0781]

======================
Epoch 56
======================
VAL SUBSET ACC : 0.6911
VAL MICRO P/R/F1: 0.7356 / 0.8594 / 0.7927
VAL MACRO P/R/F1: 0.7354 / 0.8589 / 0.7922
VAL MIN LABEL F1: 0.7787
VAL WEIGHTED F1: 0.7926
VAL HAMMING LOSS: 0.2247
Saved final: epoch 56/100

Epoch 57/100: 100%|██████████| 392/392 [01:18<00:00,  4.99it/s, loss=0.0171]

======================
Epoch 57
======================
VAL SUBSET ACC : 0.6986
VAL MICRO P/R/F1: 0.7379 / 0.8487 / 0.7894
VAL MACRO P/R/F1: 0.7379 / 0.8487 / 0.7893
VAL MIN LABEL F1: 0.7792
VAL WEIGHTED F1: 0.7896
VAL HAMMING LOSS: 0.2264
Saved final: epoch 57/100

Epoch 58/100: 100%|██████████| 392/392 [01:18<00:00,  5.01it/s, loss=0.0122]

======================
Epoch 58
======================
VAL SUBSET ACC : 0.6974
VAL MICRO P/R/F1: 0.7401 / 0.8618 / 0.7964
VAL MACRO P/R/F1: 0.7405 / 0.8609 / 0.7956
VAL MIN LABEL F1: 0.7812
VAL WEIGHTED F1: 0.7959
VAL HAMMING LOSS: 0.2204
Saved final: epoch 58/100

Epoch 59/100: 100%|██████████| 392/392 [01:18<00:00,  5.00it/s, loss=0.0231]

======================
Epoch 59
======================
VAL SUBSET ACC : 0.7007
VAL MICRO P/R/F1: 0.7413 / 0.8577 / 0.7952
VAL MACRO P/R/F1: 0.7410 / 0.8573 / 0.7949
VAL MIN LABEL F1: 0.7839
VAL WEIGHTED F1: 0.7952
VAL HAMMING LOSS: 0.2208
Saved final: epoch 59/100

Epoch 60/100: 100%|██████████| 392/392 [01:18<00:00,  4.99it/s, loss=0.0192]

======================
Epoch 60
======================
VAL SUBSET ACC : 0.7264
VAL MICRO P/R/F1: 0.7545 / 0.8409 / 0.7954
VAL MACRO P/R/F1: 0.7545 / 0.8403 / 0.7949
VAL MIN LABEL F1: 0.7845
VAL WEIGHTED F1: 0.7952
VAL HAMMING LOSS: 0.2164
Saved final: epoch 60/100

Epoch 61/100: 100%|██████████| 392/392 [01:18<00:00,  5.00it/s, loss=0.0456]

======================
Epoch 61
======================
VAL SUBSET ACC : 0.7096
VAL MICRO P/R/F1: 0.7467 / 0.8559 / 0.7975
VAL MACRO P/R/F1: 0.7467 / 0.8551 / 0.7970
VAL MIN LABEL F1: 0.7838
VAL WEIGHTED F1: 0.7973
VAL HAMMING LOSS: 0.2173
Saved final: epoch 61/100

Epoch 62/100: 100%|██████████| 392/392 [01:18<00:00,  4.99it/s, loss=0.0455]

======================
Epoch 62
======================
VAL SUBSET ACC : 0.7063
VAL MICRO P/R/F1: 0.7437 / 0.8523 / 0.7943
VAL MACRO P/R/F1: 0.7436 / 0.8517 / 0.7938
VAL MIN LABEL F1: 0.7810
VAL WEIGHTED F1: 0.7941
VAL HAMMING LOSS: 0.2207
Saved final: epoch 62/100

Epoch 63/100: 100%|██████████| 392/392 [01:18<00:00,  5.00it/s, loss=0.0146]

======================
Epoch 63
======================
VAL SUBSET ACC : 0.7213
VAL MICRO P/R/F1: 0.7517 / 0.8436 / 0.7950
VAL MACRO P/R/F1: 0.7517 / 0.8430 / 0.7946
VAL MIN LABEL F1: 0.7841
VAL WEIGHTED F1: 0.7948
VAL HAMMING LOSS: 0.2176
Saved final: epoch 63/100

Epoch 64/100: 100%|██████████| 392/392 [01:18<00:00,  5.01it/s, loss=0.0654]

======================
Epoch 64
======================
VAL SUBSET ACC : 0.7599
VAL MICRO P/R/F1: 0.7740 / 0.8224 / 0.7974
VAL MACRO P/R/F1: 0.7776 / 0.8209 / 0.7963
VAL MIN LABEL F1: 0.7816
VAL WEIGHTED F1: 0.7966
VAL HAMMING LOSS: 0.2089
Saved final: epoch 64/100

Epoch 65/100: 100%|██████████| 392/392 [01:18<00:00,  5.00it/s, loss=0.0171]

======================
Epoch 65
======================
VAL SUBSET ACC : 0.7374
VAL MICRO P/R/F1: 0.7611 / 0.8364 / 0.7970
VAL MACRO P/R/F1: 0.7623 / 0.8354 / 0.7962
VAL MIN LABEL F1: 0.7829
VAL WEIGHTED F1: 0.7965
VAL HAMMING LOSS: 0.2131
Saved final: epoch 65/100

Epoch 66/100: 100%|██████████| 392/392 [01:18<00:00,  5.01it/s, loss=0.0177]

======================
Epoch 66
======================
VAL SUBSET ACC : 0.7228
VAL MICRO P/R/F1: 0.7509 / 0.8355 / 0.7909
VAL MACRO P/R/F1: 0.7509 / 0.8348 / 0.7904
VAL MIN LABEL F1: 0.7770
VAL WEIGHTED F1: 0.7907
VAL HAMMING LOSS: 0.2208
Saved final: epoch 66/100

Epoch 67/100: 100%|██████████| 392/392 [01:18<00:00,  4.99it/s, loss=0.0181]

======================
Epoch 67
======================
VAL SUBSET ACC : 0.7075
VAL MICRO P/R/F1: 0.7453 / 0.8559 / 0.7968
VAL MACRO P/R/F1: 0.7451 / 0.8556 / 0.7965
VAL MIN LABEL F1: 0.7879
VAL WEIGHTED F1: 0.7968
VAL HAMMING LOSS: 0.2183
Saved final: epoch 67/100

Epoch 68/100: 100%|██████████| 392/392 [01:18<00:00,  4.99it/s, loss=0.00935]

======================
Epoch 68
======================
VAL SUBSET ACC : 0.7392
VAL MICRO P/R/F1: 0.7616 / 0.8331 / 0.7958
VAL MACRO P/R/F1: 0.7633 / 0.8321 / 0.7951
VAL MIN LABEL F1: 0.7850
VAL WEIGHTED F1: 0.7954
VAL HAMMING LOSS: 0.2138
Saved final: epoch 68/100

Epoch 69/100: 100%|██████████| 392/392 [01:18<00:00,  5.00it/s, loss=0.0128]

======================
Epoch 69
======================
VAL SUBSET ACC : 0.7557
VAL MICRO P/R/F1: 0.7713 / 0.8239 / 0.7967
VAL MACRO P/R/F1: 0.7720 / 0.8232 / 0.7963
VAL MIN LABEL F1: 0.7881
VAL WEIGHTED F1: 0.7965
VAL HAMMING LOSS: 0.2102
Saved final: epoch 69/100

Epoch 70/100: 100%|██████████| 392/392 [01:18<00:00,  5.00it/s, loss=0.0228]

======================
Epoch 70
======================
VAL SUBSET ACC : 0.7252
VAL MICRO P/R/F1: 0.7543 / 0.8439 / 0.7966
VAL MACRO P/R/F1: 0.7551 / 0.8430 / 0.7960
VAL MIN LABEL F1: 0.7852
VAL WEIGHTED F1: 0.7963
VAL HAMMING LOSS: 0.2155
Saved final: epoch 70/100

Epoch 71/100: 100%|██████████| 392/392 [01:18<00:00,  5.00it/s, loss=0.00406]

======================
Epoch 71
======================
VAL SUBSET ACC : 0.7144
VAL MICRO P/R/F1: 0.7490 / 0.8523 / 0.7973
VAL MACRO P/R/F1: 0.7500 / 0.8514 / 0.7967
VAL MIN LABEL F1: 0.7866
VAL WEIGHTED F1: 0.7970
VAL HAMMING LOSS: 0.2167
Saved final: epoch 71/100

Epoch 72/100: 100%|██████████| 392/392 [01:18<00:00,  5.00it/s, loss=0.00341]

======================
Epoch 72
======================
VAL SUBSET ACC : 0.6989
VAL MICRO P/R/F1: 0.7403 / 0.8586 / 0.7951
VAL MACRO P/R/F1: 0.7402 / 0.8583 / 0.7948
VAL MIN LABEL F1: 0.7787
VAL WEIGHTED F1: 0.7952
VAL HAMMING LOSS: 0.2213
Saved final: epoch 72/100

Epoch 73/100: 100%|██████████| 392/392 [01:18<00:00,  5.00it/s, loss=0.0209]

======================
Epoch 73
======================
VAL SUBSET ACC : 0.7297
VAL MICRO P/R/F1: 0.7561 / 0.8382 / 0.7951
VAL MACRO P/R/F1: 0.7565 / 0.8376 / 0.7947
VAL MIN LABEL F1: 0.7856
VAL WEIGHTED F1: 0.7949
VAL HAMMING LOSS: 0.2161
Saved final: epoch 73/100

Epoch 74/100: 100%|██████████| 392/392 [01:18<00:00,  4.99it/s, loss=0.0096]

======================
Epoch 74
======================
VAL SUBSET ACC : 0.7449
VAL MICRO P/R/F1: 0.7649 / 0.8301 / 0.7962
VAL MACRO P/R/F1: 0.7662 / 0.8291 / 0.7954
VAL MIN LABEL F1: 0.7817
VAL WEIGHTED F1: 0.7957
VAL HAMMING LOSS: 0.2125
Saved final: epoch 74/100

Epoch 75/100: 100%|██████████| 392/392 [01:18<00:00,  5.00it/s, loss=0.00161]

======================
Epoch 75
======================
VAL SUBSET ACC : 0.7455
VAL MICRO P/R/F1: 0.7645 / 0.8263 / 0.7942
VAL MACRO P/R/F1: 0.7649 / 0.8256 / 0.7938
VAL MIN LABEL F1: 0.7844
VAL WEIGHTED F1: 0.7940
VAL HAMMING LOSS: 0.2141
Saved final: epoch 75/100

Epoch 76/100: 100%|██████████| 392/392 [01:18<00:00,  5.00it/s, loss=0.0067]

======================
Epoch 76
======================
VAL SUBSET ACC : 0.7228
VAL MICRO P/R/F1: 0.7535 / 0.8475 / 0.7977
VAL MACRO P/R/F1: 0.7536 / 0.8470 / 0.7974
VAL MIN LABEL F1: 0.7896
VAL WEIGHTED F1: 0.7976
VAL HAMMING LOSS: 0.2149
Saved final: epoch 76/100

Epoch 77/100: 100%|██████████| 392/392 [01:18<00:00,  5.00it/s, loss=0.00457]

======================
Epoch 77
======================
VAL SUBSET ACC : 0.7207
VAL MICRO P/R/F1: 0.7513 / 0.8439 / 0.7949
VAL MACRO P/R/F1: 0.7513 / 0.8434 / 0.7946
VAL MIN LABEL F1: 0.7853
VAL WEIGHTED F1: 0.7948
VAL HAMMING LOSS: 0.2177
Saved final: epoch 77/100

Epoch 78/100: 100%|██████████| 392/392 [01:18<00:00,  4.99it/s, loss=0.0401]

======================
Epoch 78
======================
VAL SUBSET ACC : 0.7327
VAL MICRO P/R/F1: 0.7563 / 0.8295 / 0.7912
VAL MACRO P/R/F1: 0.7563 / 0.8291 / 0.7909
VAL MIN LABEL F1: 0.7833
VAL WEIGHTED F1: 0.7911
VAL HAMMING LOSS: 0.2189
Saved final: epoch 78/100

Epoch 79/100: 100%|██████████| 392/392 [01:18<00:00,  4.99it/s, loss=0.0269]

======================
Epoch 79
======================
VAL SUBSET ACC : 0.7054
VAL MICRO P/R/F1: 0.7442 / 0.8571 / 0.7967
VAL MACRO P/R/F1: 0.7441 / 0.8566 / 0.7963
VAL MIN LABEL F1: 0.7862
VAL WEIGHTED F1: 0.7965
VAL HAMMING LOSS: 0.2188
Saved final: epoch 79/100

Epoch 80/100: 100%|██████████| 392/392 [01:18<00:00,  4.99it/s, loss=0.00331]

======================
Epoch 80
======================
VAL SUBSET ACC : 0.7282
VAL MICRO P/R/F1: 0.7562 / 0.8430 / 0.7972
VAL MACRO P/R/F1: 0.7560 / 0.8425 / 0.7968
VAL MIN LABEL F1: 0.7857
VAL WEIGHTED F1: 0.7971
VAL HAMMING LOSS: 0.2144
Saved final: epoch 80/100

Epoch 81/100: 100%|██████████| 392/392 [01:18<00:00,  4.99it/s, loss=0.0437]

======================
Epoch 81
======================
VAL SUBSET ACC : 0.7282
VAL MICRO P/R/F1: 0.7554 / 0.8397 / 0.7954
VAL MACRO P/R/F1: 0.7552 / 0.8393 / 0.7950
VAL MIN LABEL F1: 0.7832
VAL WEIGHTED F1: 0.7953
VAL HAMMING LOSS: 0.2161
Saved final: epoch 81/100

Epoch 82/100: 100%|██████████| 392/392 [01:18<00:00,  4.99it/s, loss=0.00637]

======================
Epoch 82
======================
VAL SUBSET ACC : 0.7312
VAL MICRO P/R/F1: 0.7570 / 0.8373 / 0.7951
VAL MACRO P/R/F1: 0.7570 / 0.8368 / 0.7947
VAL MIN LABEL F1: 0.7851
VAL WEIGHTED F1: 0.7950
VAL HAMMING LOSS: 0.2158
Saved final: epoch 82/100

Epoch 83/100: 100%|██████████| 392/392 [01:18<00:00,  5.00it/s, loss=0.00615]

======================
Epoch 83
======================
VAL SUBSET ACC : 0.7222
VAL MICRO P/R/F1: 0.7533 / 0.8484 / 0.7980
VAL MACRO P/R/F1: 0.7533 / 0.8477 / 0.7975
VAL MIN LABEL F1: 0.7840
VAL WEIGHTED F1: 0.7978
VAL HAMMING LOSS: 0.2147
Saved final: epoch 83/100

Epoch 84/100: 100%|██████████| 392/392 [01:18<00:00,  4.99it/s, loss=0.00154]

======================
Epoch 84
======================
VAL SUBSET ACC : 0.7306
VAL MICRO P/R/F1: 0.7579 / 0.8436 / 0.7985
VAL MACRO P/R/F1: 0.7577 / 0.8433 / 0.7982
VAL MIN LABEL F1: 0.7895
VAL WEIGHTED F1: 0.7984
VAL HAMMING LOSS: 0.2129
Saved final: epoch 84/100

Epoch 85/100: 100%|██████████| 392/392 [01:18<00:00,  4.99it/s, loss=0.00136]

======================
Epoch 85
======================
VAL SUBSET ACC : 0.7398
VAL MICRO P/R/F1: 0.7634 / 0.8394 / 0.7996
VAL MACRO P/R/F1: 0.7634 / 0.8388 / 0.7991
VAL MIN LABEL F1: 0.7874
VAL WEIGHTED F1: 0.7994
VAL HAMMING LOSS: 0.2104
Saved final: epoch 85/100

Epoch 86/100: 100%|██████████| 392/392 [01:18<00:00,  4.99it/s, loss=0.00999]

======================
Epoch 86
======================
VAL SUBSET ACC : 0.7258
VAL MICRO P/R/F1: 0.7551 / 0.8454 / 0.7977
VAL MACRO P/R/F1: 0.7549 / 0.8451 / 0.7974
VAL MIN LABEL F1: 0.7884
VAL WEIGHTED F1: 0.7977
VAL HAMMING LOSS: 0.2144
Saved final: epoch 86/100

Epoch 87/100: 100%|██████████| 392/392 [01:18<00:00,  4.99it/s, loss=0.0194]

======================
Epoch 87
======================
VAL SUBSET ACC : 0.7231
VAL MICRO P/R/F1: 0.7528 / 0.8433 / 0.7955
VAL MACRO P/R/F1: 0.7529 / 0.8429 / 0.7953
VAL MIN LABEL F1: 0.7891
VAL WEIGHTED F1: 0.7954
VAL HAMMING LOSS: 0.2168
Saved final: epoch 87/100

Epoch 88/100: 100%|██████████| 392/392 [01:18<00:00,  5.00it/s, loss=0.0286]

======================
Epoch 88
======================
VAL SUBSET ACC : 0.7344
VAL MICRO P/R/F1: 0.7590 / 0.8361 / 0.7957
VAL MACRO P/R/F1: 0.7603 / 0.8351 / 0.7950
VAL MIN LABEL F1: 0.7841
VAL WEIGHTED F1: 0.7953
VAL HAMMING LOSS: 0.2147
Saved final: epoch 88/100

Epoch 89/100: 100%|██████████| 392/392 [01:18<00:00,  5.00it/s, loss=0.00519]

======================
Epoch 89
======================
VAL SUBSET ACC : 0.7324
VAL MICRO P/R/F1: 0.7587 / 0.8415 / 0.7980
VAL MACRO P/R/F1: 0.7596 / 0.8406 / 0.7973
VAL MIN LABEL F1: 0.7861
VAL WEIGHTED F1: 0.7976
VAL HAMMING LOSS: 0.2131
Saved final: epoch 89/100

Epoch 90/100: 100%|██████████| 392/392 [01:18<00:00,  5.00it/s, loss=0.00848]

======================
Epoch 90
======================
VAL SUBSET ACC : 0.7321
VAL MICRO P/R/F1: 0.7582 / 0.8403 / 0.7972
VAL MACRO P/R/F1: 0.7581 / 0.8398 / 0.7968
VAL MIN LABEL F1: 0.7860
VAL WEIGHTED F1: 0.7970
VAL HAMMING LOSS: 0.2138
Saved final: epoch 90/100

Epoch 91/100: 100%|██████████| 392/392 [01:18<00:00,  5.01it/s, loss=0.00145]

======================
Epoch 91
======================
VAL SUBSET ACC : 0.7410
VAL MICRO P/R/F1: 0.7616 / 0.8272 / 0.7930
VAL MACRO P/R/F1: 0.7615 / 0.8268 / 0.7927
VAL MIN LABEL F1: 0.7839
VAL WEIGHTED F1: 0.7929
VAL HAMMING LOSS: 0.2159
Saved final: epoch 91/100

Epoch 92/100: 100%|██████████| 392/392 [01:19<00:00,  4.93it/s, loss=0.00665]

======================
Epoch 92
======================
VAL SUBSET ACC : 0.7473
VAL MICRO P/R/F1: 0.7660 / 0.8272 / 0.7954
VAL MACRO P/R/F1: 0.7667 / 0.8264 / 0.7950
VAL MIN LABEL F1: 0.7862
VAL WEIGHTED F1: 0.7952
VAL HAMMING LOSS: 0.2128
Saved final: epoch 92/100

Epoch 93/100: 100%|██████████| 392/392 [01:18<00:00,  4.99it/s, loss=0.00101]

======================
Epoch 93
======================
VAL SUBSET ACC : 0.7321
VAL MICRO P/R/F1: 0.7580 / 0.8391 / 0.7965
VAL MACRO P/R/F1: 0.7578 / 0.8388 / 0.7962
VAL MIN LABEL F1: 0.7868
VAL WEIGHTED F1: 0.7964
VAL HAMMING LOSS: 0.2144
Saved final: epoch 93/100

Epoch 94/100: 100%|██████████| 392/392 [01:18<00:00,  4.98it/s, loss=0.0407]

======================
Epoch 94
======================
VAL SUBSET ACC : 0.7428
VAL MICRO P/R/F1: 0.7646 / 0.8352 / 0.7983
VAL MACRO P/R/F1: 0.7653 / 0.8344 / 0.7978
VAL MIN LABEL F1: 0.7865
VAL WEIGHTED F1: 0.7980
VAL HAMMING LOSS: 0.2110
Saved final: epoch 94/100

Epoch 95/100: 100%|██████████| 392/392 [01:18<00:00,  4.99it/s, loss=0.00603]

======================
Epoch 95
======================
VAL SUBSET ACC : 0.7380
VAL MICRO P/R/F1: 0.7609 / 0.8337 / 0.7957
VAL MACRO P/R/F1: 0.7609 / 0.8333 / 0.7954
VAL MIN LABEL F1: 0.7878
VAL WEIGHTED F1: 0.7956
VAL HAMMING LOSS: 0.2141
Saved final: epoch 95/100

Epoch 96/100: 100%|██████████| 392/392 [01:18<00:00,  4.99it/s, loss=0.00035]

======================
Epoch 96
======================
VAL SUBSET ACC : 0.7392
VAL MICRO P/R/F1: 0.7621 / 0.8352 / 0.7970
VAL MACRO P/R/F1: 0.7621 / 0.8347 / 0.7966
VAL MIN LABEL F1: 0.7877
VAL WEIGHTED F1: 0.7969
VAL HAMMING LOSS: 0.2128
Saved final: epoch 96/100

Epoch 97/100: 100%|██████████| 392/392 [01:19<00:00,  4.94it/s, loss=0.0185]

======================
Epoch 97
======================
VAL SUBSET ACC : 0.7383
VAL MICRO P/R/F1: 0.7610 / 0.8331 / 0.7954
VAL MACRO P/R/F1: 0.7611 / 0.8327 / 0.7951
VAL MIN LABEL F1: 0.7872
VAL WEIGHTED F1: 0.7953
VAL HAMMING LOSS: 0.2143
Saved final: epoch 97/100

Epoch 98/100: 100%|██████████| 392/392 [01:19<00:00,  4.94it/s, loss=0.00316]

======================
Epoch 98
======================
VAL SUBSET ACC : 0.7315
VAL MICRO P/R/F1: 0.7576 / 0.8391 / 0.7963
VAL MACRO P/R/F1: 0.7576 / 0.8387 / 0.7960
VAL MIN LABEL F1: 0.7875
VAL WEIGHTED F1: 0.7962
VAL HAMMING LOSS: 0.2147
Saved final: epoch 98/100

Epoch 99/100: 100%|██████████| 392/392 [01:18<00:00,  4.99it/s, loss=0.00325]

======================
Epoch 99
======================
VAL SUBSET ACC : 0.7342
VAL MICRO P/R/F1: 0.7591 / 0.8376 / 0.7964
VAL MACRO P/R/F1: 0.7591 / 0.8372 / 0.7962
VAL MIN LABEL F1: 0.7883
VAL WEIGHTED F1: 0.7963
VAL HAMMING LOSS: 0.2141
Saved final: epoch 99/100

Epoch 100/100: 100%|██████████| 392/392 [01:18<00:00,  5.00it/s, loss=0.0153]

======================
Epoch 100
======================
VAL SUBSET ACC : 0.7321
VAL MICRO P/R/F1: 0.7577 / 0.8379 / 0.7958
VAL MACRO P/R/F1: 0.7575 / 0.8377 / 0.7956
VAL MIN LABEL F1: 0.7884
VAL WEIGHTED F1: 0.7958
VAL HAMMING LOSS: 0.2150
Saved final: epoch 100/100

In [24]:
if FINAL_TRAINING_COMPLETE and not SESSION_STOPPED:
    val_result = evaluate(
        final_model,
        val_loader
    )

    best_thresholds = optimize_thresholds(
        val_result["labels"],
        val_result["probs"]
    )

    val_result_tuned = evaluate(
        final_model,
        val_loader,
        best_thresholds
    )

    print("\n======================")
    print("BEST THRESHOLDS FROM FINAL VALIDATION")
    print("======================")

    for label, thr in zip(
        LABEL_COLUMNS,
        best_thresholds
    ):
        print(f"{label}: {thr:.3f}")

    print("\nVALIDATION RESULT AFTER THRESHOLD TUNING")
    print("macro_f1:", val_result_tuned["macro_f1"])
    print("micro_f1:", val_result_tuned["micro_f1"])
    print("min_per_label_f1:", val_result_tuned["min_per_label_f1"])
    print("subset_accuracy:", val_result_tuned["subset_accuracy"])

======================
BEST THRESHOLDS FROM FINAL VALIDATION
======================
depression: 0.240
no_depression: 0.200

VALIDATION RESULT AFTER THRESHOLD TUNING
macro_f1: 0.7956192249503533
micro_f1: 0.7957966486793524
min_per_label_f1: 0.7883551673944688
subset_accuracy: 0.7320574162679426

In [25]:
if FINAL_TRAINING_COMPLETE and not SESSION_STOPPED:
    def summarize_result(name, result):

        return {
            "split": name,
            "subset_accuracy_exact_match": result["subset_accuracy"],
            "micro_precision": result["micro_precision"],
            "micro_recall": result["micro_recall"],
            "micro_f1": result["micro_f1"],
            "macro_precision": result["macro_precision"],
            "macro_recall": result["macro_recall"],
            "macro_f1": result["macro_f1"],
            "weighted_f1": result["weighted_f1"],
            "min_per_label_f1": result["min_per_label_f1"],
            "hamming_loss": result["hamming_loss"]
        }


    train_result = evaluate(
        final_model,
        train_eval_loader,
        best_thresholds
    )

    val_result_final = evaluate(
        final_model,
        val_loader,
        best_thresholds
    )

    test_result = evaluate(
        final_model,
        test_loader,
        best_thresholds
    )

    metrics_summary = pd.DataFrame([
        summarize_result("train", train_result),
        summarize_result("validation", val_result_final),
        summarize_result("test", test_result)
    ])

    print("\n======================")
    print("FINAL METRICS SUMMARY")
    print("======================")
    display(metrics_summary)

    print("\n======================")
    print("BEST THRESHOLDS")
    print("======================")

    threshold_df = pd.DataFrame({
        "label": LABEL_COLUMNS,
        "threshold": best_thresholds
    })

    display(threshold_df)

    print("\n======================")
    print("TEST SET MAIN RESULT")
    print("======================")

    print(f"Subset Accuracy / Exact Match : {test_result['subset_accuracy']:.4f}")
    print(f"Micro Precision              : {test_result['micro_precision']:.4f}")
    print(f"Micro Recall                 : {test_result['micro_recall']:.4f}")
    print(f"Micro F1                     : {test_result['micro_f1']:.4f}")
    print(f"Macro Precision              : {test_result['macro_precision']:.4f}")
    print(f"Macro Recall                 : {test_result['macro_recall']:.4f}")
    print(f"Macro F1                     : {test_result['macro_f1']:.4f}")
    print(f"Weighted F1                  : {test_result['weighted_f1']:.4f}")
    print(f"Min Per-label F1             : {test_result['min_per_label_f1']:.4f}")
    print(f"Hamming Loss                 : {test_result['hamming_loss']:.4f}")

======================
FINAL METRICS SUMMARY
======================

,split,subset_accuracy_exact_match,micro_precision,micro_recall,micro_f1,macro_precision,macro_recall,macro_f1,weighted_f1,min_per_label_f1,hamming_loss
0,train,0.997488,0.997494,0.999920,0.998706,0.997473,0.999922,0.998696,0.998706,0.998287,0.001296
1,validation,0.732057,0.757707,0.837919,0.795797,0.757543,0.837726,0.795619,0.795793,0.788355,0.215012
2,test,0.706481,0.739100,0.831505,0.782584,0.738933,0.831377,0.782424,0.782614,0.774416,0.231007

======================
BEST THRESHOLDS
======================

           label  threshold
0     depression       0.24
1  no_depression       0.20

======================
TEST SET MAIN RESULT
======================
Subset Accuracy / Exact Match : 0.7065
Micro Precision              : 0.7391
Micro Recall                 : 0.8315
Micro F1                     : 0.7826
Macro Precision              : 0.7389
Macro Recall                 : 0.8314
Macro F1                     : 0.7824
Weighted F1                  : 0.7826
Min Per-label F1             : 0.7744
Hamming Loss                 : 0.2310

In [26]:
if FINAL_TRAINING_COMPLETE and not SESSION_STOPPED:
    print("\n======================")
    print("TEST CLASSIFICATION REPORT")
    print("======================")

    report_dict = classification_report(
        test_result["labels"],
        test_result["preds"],
        target_names=LABEL_COLUMNS,
        zero_division=0,
        output_dict=True
    )

    per_label_report = pd.DataFrame(report_dict).T
    display(per_label_report)

    per_label_metrics = pd.DataFrame({
        "label": LABEL_COLUMNS,
        "precision": test_result["per_label_precision"],
        "recall": test_result["per_label_recall"],
        "f1_score": test_result["per_label_f1"],
        "true_support": test_result["labels"].sum(axis=0).astype(int),
        "predicted_positive": test_result["preds"].sum(axis=0).astype(int),
        "threshold": best_thresholds
    })

    print("\n======================")
    print("PER-LABEL TEST METRICS")
    print("======================")
    display(per_label_metrics)

    print("\n======================")
    print("TEST MULTI-LABEL CONFUSION MATRIX")
    print("======================")

    mcm = multilabel_confusion_matrix(
        test_result["labels"],
        test_result["preds"]
    )

    confusion_rows = []

    for i, label in enumerate(LABEL_COLUMNS):
        tn, fp, fn, tp = mcm[i].ravel()

        confusion_rows.append({
            "label": label,
            "TP": int(tp),
            "FP": int(fp),
            "FN": int(fn),
            "TN": int(tn)
        })

    confusion_df = pd.DataFrame(confusion_rows)
    display(confusion_df)

    test_probs_df = pd.DataFrame(
        test_result["probs"],
        columns=[f"prob_{label}" for label in LABEL_COLUMNS]
    )

    test_preds_df = pd.DataFrame(
        test_result["preds"],
        columns=[f"pred_{label}" for label in LABEL_COLUMNS]
    )

    test_true_df = test_df[[TEXT_COLUMN] + LABEL_COLUMNS].copy()

    test_predictions_output = pd.concat(
        [
            test_true_df.reset_index(drop=True),
            test_probs_df.reset_index(drop=True),
            test_preds_df.reset_index(drop=True)
        ],
        axis=1
    )

    metrics_summary.to_csv(
        "/kaggle/working/mbert_thai_depression_metrics_summary.csv",
        index=False,
        encoding="utf-8-sig"
    )

    threshold_df.to_csv(
        "/kaggle/working/mbert_thai_depression_thresholds.csv",
        index=False,
        encoding="utf-8-sig"
    )

    per_label_report.to_csv(
        "/kaggle/working/mbert_thai_depression_per_label_report.csv",
        encoding="utf-8-sig"
    )

    per_label_metrics.to_csv(
        "/kaggle/working/mbert_thai_depression_per_label_metrics.csv",
        index=False,
        encoding="utf-8-sig"
    )

    confusion_df.to_csv(
        "/kaggle/working/mbert_thai_depression_confusion_matrix.csv",
        index=False,
        encoding="utf-8-sig"
    )

    test_predictions_output.to_csv(
        "/kaggle/working/mbert_thai_depression_test_predictions.csv",
        index=False,
        encoding="utf-8-sig"
    )

    print("\nEXPORTED FILES")
    print("/kaggle/working/mbert_thai_depression_metrics_summary.csv")
    print("/kaggle/working/mbert_thai_depression_thresholds.csv")
    print("/kaggle/working/mbert_thai_depression_per_label_report.csv")
    print("/kaggle/working/mbert_thai_depression_per_label_metrics.csv")
    print("/kaggle/working/mbert_thai_depression_confusion_matrix.csv")
    print("/kaggle/working/mbert_thai_depression_test_predictions.csv")

======================
TEST CLASSIFICATION REPORT
======================

               precision    recall  f1-score  support
depression      0.748954  0.836774  0.790432   2567.0
no_depression   0.728911  0.825980  0.774416   2448.0
micro avg       0.739100  0.831505  0.782584   5015.0
macro avg       0.738933  0.831377  0.782424   5015.0
weighted avg    0.739170  0.831505  0.782614   5015.0
samples avg     0.768993  0.831505  0.789831   5015.0

======================
PER-LABEL TEST METRICS
======================

,label,precision,recall,f1_score,true_support,predicted_positive,threshold
0,depression,0.748954,0.836774,0.790432,2567,2868,0.24
1,no_depression,0.728911,0.825980,0.774416,2448,2774,0.20

======================
TEST MULTI-LABEL CONFUSION MATRIX
======================

           label    TP   FP   FN    TN
0     depression  2148  720  419  1728
1  no_depression  2022  752  426  1815

EXPORTED FILES
/kaggle/working/mbert_thai_depression_metrics_summary.csv
/kaggle/working/mbert_thai_depression_thresholds.csv
/kaggle/working/mbert_thai_depression_per_label_report.csv
/kaggle/working/mbert_thai_depression_per_label_metrics.csv
/kaggle/working/mbert_thai_depression_confusion_matrix.csv
/kaggle/working/mbert_thai_depression_test_predictions.csv

In [27]:
if FINAL_TRAINING_COMPLETE and not SESSION_STOPPED:
    SAVE_PATH = "/kaggle/working/final_mbert_thai_depression_xtransformers_strong_optimized.pt"

    torch.save(
        {
            "model_state_dict": final_model.state_dict(),
            "thresholds": best_thresholds,
            "best_params": best_params,
            "labels": LABEL_COLUMNS,
            "model_name": MODEL_NAME,
            "max_len": MAX_LEN,
            "dataset": "Thai Depression (original train/valid/test JSON)",
            "seed": SEED,
            "epochs": EPOCHS,
            "batch_size": BATCH_SIZE,
            "optuna_trials": N_TRIALS,
            "optuna_epochs": OPTUNA_EPOCHS,
            "objective": "0.45 macro_f1 + 0.25 micro_f1 + 0.20 min_per_label_f1 + 0.10 subset_accuracy",
            "note": "Encoder comparison version; encoder frozen; same Strong Optimized EAQD/x-transformers framework."
        },
        SAVE_PATH
    )

    print("\nMODEL SAVED:", SAVE_PATH)

MODEL SAVED: /kaggle/working/final_mbert_thai_depression_xtransformers_strong_optimized.pt

In [28]:

print("Resume file:", CHECKPOINT_PATH)
print("Latest trial results:", WORK_DIR / "trials_latest.csv")
saved = CHECKPOINT.get("training")
if saved:
    print("Saved stage:", saved["tag"], "completed epochs:", saved["completed_epochs"])
print("Attach this run's saved Output as Input in the next session to resume.")

Resume file: /kaggle/working/checkpoint_latest.pt
Latest trial results: /kaggle/working/trials_latest.csv
Saved stage: final completed epochs: 100
Attach this run's saved Output as Input in the next session to resume.